### ISSUE TITLE
NPC and Character Sheets do not render properly on Firefox

### ISSUE THREAD

**Issue by inklikeurine** [xdy/twodsix-foundryvtt#1004]
**Before you create the bug report**
* Have you checked that this issue hasn't already been reported on https://github.com/xdy/twodsix-foundryvtt/issues? 
**Yes** 
* Have you tried with all Foundry modules disabled?
**Yes**
* Have you tried to update your browser? (Do note that Safari is not supported).
**Yes**

**Describe the bug**
The NPC Sheet, Traveller Sheet, and Ship Sheet are not rendering properly on Firefox. The issue is not present on Edge or Google Chrome.
This issue persists with all modules unloaded, and all modules loaded.

**To Reproduce**
1. open Firefox
2. log into game
3. open character sheet

**Expected behavior**
Sheet rendering should be the same across all browsers.

**Screenshots**
![PC-Sheet](https://user-images.githubusercontent.com/15773029/168400526-f675e63c-939c-4805-976a-5c49eca8f3e0.png)
![NPC-sheet](https://user-images.githubusercontent.com/15773029/168400545-663ac237-78b0-49c6-9e7e-3ed67942ce3e.png)
![Ship-Sheet](https://user-images.githubusercontent.com/15773029/168400557-7130eb48-c1f3-4926-8306-8e8796d83549.png)

**Environment (please complete the following information):**
 - OS and browser: **Foundry is running in Docker, on a Linux Mint Machine. Accessed via Firefox v100.0**
 - How you run Foundry: **Via docker, accessed via web.**
 - Foundry version: **Version 9, Build 269**
 - System version: **1.42.1**
 - Installed modules: 
![Modules-pt1](https://user-images.githubusercontent.com/15773029/168400595-1604bad0-0e60-4af0-993c-73d231053319.png)
![Modules-pt2](https://user-images.githubusercontent.com/15773029/168400604-ee70337a-8852-4172-a2fc-6fba29dd5789.png)
![Modules-pt3](https://user-images.githubusercontent.com/15773029/168400614-52238c9a-e077-4cce-8693-b17cc1f5fcb1.png)

**Comment by marvin9257** [comment]
Does this only happen when using Foundry default style or also when using the standard Twodsix dark style as well?  I can't reproduce this issue on Mac with Firefox (the alignment issue are much more minor.)

**Comment by inklikeurine** [comment]
I ran a game last Friday and it seems to be exclusive to me. All my players only reported everything being fine on multiple different computers/browsers (Firefox/Chrome).

I believe this issue to be exclusively on my end. I suspect it is because I have the windows UI scale set to 125%. 

Please feel free to close the issue.
