### ISSUE TITLE
Ammunition / Magazines

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1146]
**Is your feature request related to a problem? Please describe.**
The damage of a weapon is set in the item. But it is often the case that there are different types of ammunition and then the damage, traits and AP adeviate from the original values.

This is currently not taken into account because only the damage of the weapon item is relevant. That's why you always have to do the math and think about it beforehand if you have loaded a different ammunition. This can easily be forgotten and lead to unnecessary discussions at the vTable.

**Describe the solution you'd like**
Values ​​(damage, AP) of the loaded "consumable item" o
![Unbenannt-2](https://user-images.githubusercontent.com/97696599/194885847-def0fc94-3f42-49e2-b830-6704702057df.png)
verrule the specifications of the weapon item.

Logically, instead of "consumables" there would be a separate, new type such as. "Ammunition" where all relevant fields are present.

In the equipment listing, the magazine should then be directly clickable (to the sheet) and the damage should be rollable. If there is an AP >=1 than it shopuld be display too. -> see attached image.

**Comment by marvin9257** [comment]
So the Armor Piercing property exists on both the actor and consumable.  The net AP value is the sum of the weapon and consumable value.  The community agreed to adding rather than overriding when feature was created.  I can look to see whether adding bonus damage property to the consumable is possible.

**Comment by RomKre** [comment]
Ok. 
- AP: Checked and I had an error in an experimental order - sorry! 
- Adding or overwriting damage would be great.
