### ISSUE TITLE
Referee can set Difficulty

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1201]
I often have the situation that I don't give the players any information about the difficulty of the throw. Most of the time I don't want to tell them how big the hurdle etc. is. In addition, it interrupts the flow when you always have to say how difficult something is.

Of course I can think along and e.g. recalculate the effect, but it would be nicer if I, as the referee, could select the difficulty covertly. After a throw only the referee would see everything correctly (effect) and the player would only see the numerical result.
The player then only knows from my telling or the reaction whether he has made it or not.

- You could make a drop down below the chat window where the referee could select the difficulty for all the clients/players.
- A difficulty of 8 is always automatically used for attack rolls - this way you don't have to switch between difficulties in combat.

**Comment by marvin9257** [comment]
I'm thinking that this feature would be better as a macro rather than in the core code.  There really isn't a menu option for Twodsix.  And a macro would allow for the GM to have more control.  Will think on it some more.
