### ISSUE TITLE
Encumbrance calculation incorrect.

### ISSUE THREAD

**Issue by emattsen** [xdy/twodsix-foundryvtt#1207]
**Describe the bug**
The ratio when encumbrance effects movement is calculated at 1/6 of actorData.encumbrance.max when it should be 1/3 of that value.

**Expected behavior**
Change bolded code below to actorData.encumbrance.max / 3

**Code**
From twodsix.bundle.js, lines 5298 to 5213:

          case "OTHER":
            if (actorData.encumbrance.value > actorData.encumbrance.max && game.settings.get("twodsix", "useEncumbrance")) {
              return [];
            } else if (actorData.encumbrance.value > actorData.encumbrance.max / 2 && game.settings.get("twodsix", "useEncumbrance")) {
              return [
                { range: 1.5, color: "walk" }
              ];
            } else if (actorData.encumbrance.value > **actorData.encumbrance.max / 6** && game.settings.get("twodsix", "useEncumbrance")) {
              movementSpeed *= 0.75;
            }
            return [
              { range: movementSpeed, color: "walk" },
              { range: movementSpeed * 2, color: "dash" },
              { range: movementSpeed * 3, color: "run" }
            ];

**Additional context**
Issue discussed with user #marvin9257 on discord on 12/21/2022.

**Comment by marvin9257** [comment]
The encumbrance calculation is correct for CE (as discussed on the Discord).  But it would be helpful to add some settings so that the OTHER rules set can be adjusted.
