### ISSUE TITLE
Space-Object Sheet 

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1211]
**Is your feature request related to a problem? Please describe.**
No problem :) Just to make referees life easier.

**Describe the solution you'd like**
1) "Tech Level" textfield
2) "Features/Traits" textfield
3) "Count" field (like "Count: [ 1 ] / [ 1 ] active"; [ x ] are textfields)
4) "Thrust" and "Rounds" added as a movement unit
5) Button/Dice-icon to make an attack roll; for every active object (see pt. 3) DM+1 automatically added to he roll; then an option to edit the formula or add another DM.

**Comment by marvin9257** [comment]
Not certain how to address 4),  A movement unit must be a distance. These are additional movement units?  Maybe an example would help.  Thanks.
