### ISSUE TITLE
Weapons: Active Magazine

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1213]
**Is your feature request related to a problem? Please describe.**
A hidden feature is that you can select the active magazine at the bottom of the weapon sheet. Unfortunately, this is often overlooked or not considered.

**Describe the solution you'd like**
1) One solution would be to place the dropdown field at the top of the sheet, e.g. below "Assign Skill". Also I would rename it since "consumables" is a very technical term. Just label the dropdown as "Active Magazine".

2) In addition, a marker in the overview that shows the "active" magazine would be great.

As examples I made small picture montages.
![twodsix_3](https://user-images.githubusercontent.com/97696599/210137253-69fc17cd-bf41-4819-be79-82851acf36d3.png)
![twodsix_2](https://user-images.githubusercontent.com/97696599/210137254-17af48f3-45b8-4926-9d47-fa6311c88505.png)

**Comment by RomKre** [comment]
Another thought: If you click the "inactive marker" of a magazine/icon, you can activate that one and deactivate the others.

This allows you to quickly switch around (weapons with multiple ammo types, grenade launchers, etc.) and doesn't always have to go into the respective sheet. You could completely omit the dropdown for the magazine selection!

**Comment by marvin9257** [comment]
Almost have this one done.  I'm not going to change the weapon sheet for now as I think it needs a total reorganization.  Possibly with tabs (although I'm not a fan of tabs).
