### ISSUE TITLE
Mass of Worn Armor

### ISSUE THREAD

**Issue by Gunbunny** [xdy/twodsix-foundryvtt#1218]
Good eve!  I'd like to request adding support to worn armor weighing less while equipped.  From page 98 in the Traveller 2022 Core rulebook, "The mass of armour is distributed around the body when worn properly, thus reducing its effective weight.  You can reduce the mass of armour being worn by 75% for the purposes of encumbrance."

It doesn't appear to be coded that way, as the weight of armor doesn't change when equipped versus when it's carried.   Is this possible?

Thanks,

GBFF

**Comment by Simyonovich** [comment]
Yeah, this is pretty important, considering that these weights are automated, so right now we have to create worn and non-worn versions of these items.

**Comment by Gunbunny** [comment]
OK.  If you need any help, please let me know.  While I don't code (well), I'd happily do data entry.  Thanks a lot!

**Comment by Simyonovich** [comment]
just echoing your concern on this, as it's pretty important rule.
data entry is also the only skill I could bring in to help.

**Comment by marvin9257** [comment]
This feature is already built into the system.  If you go to the bottom of the main Twodsix settings menu you should see this.
<img width="577" alt="Screenshot 2023-01-16 at 7 14 14 AM" src="https://user-images.githubusercontent.com/72580196/212686965-0c99d62d-f2e5-4537-81a3-8b88e066ecf8.png">
When the armor is equipped, you should see the encumbrance decrese.  For this example, armor weighs 25% when worn.
