### ISSUE TITLE
Characteristic bonuses and penalties not implemented within item creation?

### ISSUE THREAD

**Issue by Simyonovich** [xdy/twodsix-foundryvtt#1229]
**Is your feature request related to a problem? Please describe.**

Augments, powered armour, drugs, etc don't seem to have any functionality when it comes to providing Statistic bonuses or penalties; ie +2 to Strength or -2 to Dex. There are a myriad of items, add-ons, mods, etc that apply these bonuses and penalties and not being able to implement these makes automation inconsistent and confusing.

**Describe the solution you'd like**

Please provide a field for items, similar to the associated skill and skill bonus fields, where characteristics can be modified by equipped items.

**Describe alternatives you've considered**

**Additional context**
If the feature request relates to rules, quotes from and/or links to **OGL** rules (such as Cepheus Engine) are very helpful as we cannot implement features for non-OGL rulesets.

**Comment by marvin9257** [comment]
This will be resolved when active effects are implemented.

**Comment by Simyonovich** [comment]
hey, that's awesome. glad to hear it's being worked on. thanks so much for everyone's hard work. the system overall is so much fun to work with.

**Comment by marvin9257** [comment]
Yes, you'll make an active effect on the item to modify attributes
