### ISSUE TITLE
Support computers - Bandwith

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1248]
**Is your feature request related to a problem? Please describe.**
No. It would just be cool :)

**Describe the solution you'd like**
Computers (item and ship components) have a "Processing score". All software (item and ship) has a "Bandwidth score", which represents the processing power a computer requires in order to run it.

It would be cool, if twodsix supports this fundamental mechanic. As far as I know is this part of all Scifi Traveller rulesets.

So what would be needed?
For Items:
- New Item Type "Computer" with a field for Processing Score
- New Item Type "Software" with a field for Bandwith Score which is attachable to another Item like ammo.
- If motivated, than an automation to see the available and used bandwith for the computer item :)

For Ships:
- Processing Score field for Computer components
- Bandwith Score field for Software components
- On the components table a new column to show the processing/bandwith like with power -> "+" as a prefix to indicate processing score.
- Maybe a new field at the overview (where Hull, Armor, Fuel is displayed) where you can see current used Bandwith (all active software components) and max Bandwith (all active computer components).

**Comment by marvin9257** [comment]
This issue will have to wait until Foundry VTT supports embedded items in items.

**Comment by RomKre** [comment]
MAybe just a lite version? Only the fields and the column to see if Bantwith ist needed/produced - without function an calculations etc.?

**Comment by marvin9257** [comment]
Yes, I think that would be doable - add bandwidth fields and maybe some summary calcs.  The question is where to put the totals on the ship sheet.  I could get rid of the shield symbol for the ship hull and put both hull and bandwidth there.  I'm reluctant to get rid of the graphic, however.
