### ISSUE TITLE
Add the ability to enter a minimum required characteristic for weapons, and modifiers if too low/just right/too high

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#129]
**Is your feature request related to a problem? Please describe.**
Mostly to support the original version of the game.

**Describe the solution you'd like**
Add a dropdown with characteristics, and edit fields for value, too low penalty, just right bonus and too high bonus. :)

**Describe alternatives you've considered**
Have people remember to do this manually.

**Additional context**
The edit fields above might be just one field that gets parsed (like "-2/+1/+3")
The ability to see these fields might be gated behind a system setting.

**Comment by engleback** [comment]
For Classic Traveller, each weapon has:
1. a characteristic/attribute, this is either STR for melee (blade) weapons and DEX for guns
2. a required attribute value, e.g. DEX 6-
3. a penalty if the required attribute is not met
4. an advantageous attribute value, e.g. DEX 10+
5. a bonus if the advantageous value is met

For example, a Laser Carbine has DEX 6-/-3 and 10+/+2, meaning DEX 6 or less gives a DM of -3 and DEX 10 or more gives a DM of +2.

Note this is per weapon.

These are in addition to the associated skill adjustments.

Classic Traveller does not use standard attribute modifiers, they are arbitary.
