### ISSUE TITLE
Add context to dropped-in consumables such as Ammunition

### ISSUE THREAD

**Issue by geoffwasham** [xdy/twodsix-foundryvtt#1305]
If I create a Consumable/Magazine for an ammo type, for example: "Armour Piercing," and then drop it onto a weapon attached to one of my Traveller's sheets, the ammo appears in the weapon entry as simply "Armour Piercing," as it should. However, the Consumables section lists "Armour Piercing" without any context as to what that represents.

## My request would be to have the ammo under Consumables listed in the following format:
"Magazine: {weapon name} ({ammo name})"
For example:
"Magazine: Advanced Combat Rifle (Armour Piercing)"

Preferably without changing the behavior of the consumables listed in the weapon entry itself.

## The workarounds for this are as follows:
Reload the weapon using the existing mechanic, then edit the magazine added to change the name and statistics (if any) for the new ammo. This is playable, but slower.

Alternatively, I could create existing Magazine Consumable items for each weapon, for each ammo type said weapon can use. Ain't nobody got time for that.

**Comment by marvin9257** [comment]
How about this format?  Ammo Name (weapon/parent item name).  Some consumables might be carried and not attached.  This way I don't need to handle as an exception. The consumable type is already listed in the column left of the name
<img width="477" alt="Screenshot 2023-05-06 at 1 06 47 PM" src="https://user-images.githubusercontent.com/72580196/236640022-6e02fa26-a741-471f-8692-934bf0ce1e42.png">
