### ISSUE TITLE
Augmentations

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1310]
**Is your feature request related to a problem? Please describe.**
1) Players are only transporting augmentations and not using/mounting them. Every Augment Item has a AE effect which is messing up the rolls. 
2) Player X is using 3 different types of attachable arm prosthetics (Items with AE). When switching, he has to delete the nopt used items and drag&drop if usied again.

**Describe the solution you'd like**
Like with Armour and Weapons, make it possible to change if an augmentation item is equipped-backpack-ship. Only when equipped, the AE is set to active. 

EDIT:  The weight of an augmentation should generally also be taken into account.

**Describe alternatives you've considered**

**Comment by marvin9257** [comment]
You can turn the AE off if you go to the effects tab and click on the circle x.  This disables the effect but does not delete it.![image](https://user-images.githubusercontent.com/72580196/235456760-6263887e-b441-41dc-84a6-f703e0d581d2.png)

**Comment by marvin9257** [comment]
For #2, need to consider adding "equipped" state for augments
