### ISSUE TITLE
Renamed AE and unknow source

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1311]
**Describe the bug**
In a compendium I have an armor item (called "Battle Dress, Basic") with an active effect (named "Battle Dress Bonus"). As soon as I give the armor item to an actor, the label of the AE changes to the name of the armor item and the "source" shows as unknown.

**Expected behavior**
- Label of the AE should not change
- source should be the parent item

**Comment by marvin9257** [comment]
We'll address these issues after v11 stable drops - due to the changes in the way it handles these features.
