### ISSUE TITLE
Issues in Auto calculate of summary ship power, weight, etc

### ISSUE THREAD

**Issue by sharcashmo** [xdy/twodsix-foundryvtt#1316]
Hi,

I have found some minor issues in power and price calculation:

- Power calculation:
1. Drive power consumption is added to "Systems" total amount, not to M-Drive & J-Drive. I guess this part is still under development and sooner than later it will be a way to signal the components to be M-Drive or J-Drive, instead of just "Drive"

- Price calculation
1. Elements which price is a "percent of base hull value" do not multiply the item cost per its quantity. So, I added 4 points of armor to a ship, which 5% of base hull value cost per point, so I set quantity to 4 and the price was exactly the same than having quantity to 1.
2. Vehicle components don't add their price to the total ship price. Their weight is, thought, but their price not.

Regards!

sharcashmo (aka David)

**Comment by marvin9257** [comment]
Hi, thanks for the feedback.  Some answers:
For the power calc of Drives, if you put j-drive or m-drive in the component name it will allocated it to the corresponding field.

For price calcs
1) I've debated this for a while whether quantity makes sense here.  I've thought that folks would multiply it out - in your example 20%.  But I should either omit the qty field or do the math.  I'll try to fix this in an upcoming update.

2) The price calcs for ships originally included vehicle costs, but the overwhelming response from the community was that it should not be included to not throw off mortgage and maintenance costs.  So it is excluded.

**Comment by marvin9257** [comment]
I think I have a solution to the "percent of base hull value" issue.  I'll create an additional pricing option, "percent of base hull value per unit" to cover cases you note.  This way, the calcs will still work for existing ships.  Thanks.

**Comment by sharcashmo** [comment]
Great!

it makes sense what you say about the vehicles included in the price. It was just because of consistence with the Traveller manuals.

About drivers, I will try with naming them j-drive and m-drive, although this will break localization a bit (i am spanish speaker and all items, abilities, actors, etc have spanish names in my games :D).

Thanks ;)
