### ISSUE TITLE
Unable to install the module on Foundry Version 10. 

### ISSUE THREAD

**Issue by jax7778** [xdy/twodsix-foundryvtt#1366]
**Before you create the bug report**
* Have you checked that this issue hasn't already been reported on https://github.com/xdy/twodsix-foundryvtt/issues?
I apologize, I did not see it listed. 
* Have you tried with all Foundry modules disabled?
I don't believe this is applicable in this case. 
* Have you tried to update your browser? (Do note that Safari is not supported).
Tried multiple browsers, but I don't believe this is the issue

**Describe the bug**
It doesn't appear that we are able to install this system on foundry version 10 any longer. Like any people, I am not able to upgrade to version 11 just yet, and I am getting an error when trying to install this module on version 10.  It looks like there was support for version 10, is there no option to install an older version for 10?

**To Reproduce**
Attempt to install the system on foundry version 10

**Expected behavior**
The system should install .

**Screenshots**

**Environment (please complete the following information):**
 - OS and browser: [e.g. 'Windows 10' or 'Ubuntu 20.04']
 - How you run Foundry [e.g. 'Foundry client' or 'Chrome']
![image](https://github.com/xdy/twodsix-foundryvtt/assets/83039897/1196b3e5-97cb-41ac-b938-173cdbb2ac1b)

 - Foundry version [e.g. 0.7.9]
 - 10.291
 - System version [e.g. 0.6.82]
 - The store lists it as 2.32.4 but the error referred to 3.2.0
 - Installed modules [e.g. None]

**Additional context**

**Comment by jax7778** [comment]
> It seems the manifest on the FVTT is incorrect. Please try to load the system manually with this manifest link: https://github.com/xdy/twodsix-foundryvtt/releases/download/v2.32.4/system.json

Thanks, that manifest works. After some research I did discover  you can also download the last version for 10 and upload the whole folder to your systems directory. But this is a lot easier. Thanks for the info.

**Comment by marvin9257** [comment]
@xdy has now fixed the manifest.
