### ISSUE TITLE
Players cannot add Weapon Attachments from Compendium

### ISSUE THREAD

**Issue by bryshen** [xdy/twodsix-foundryvtt#1410]
When a Player or Trusted Player tries to add a weapon attachment from a compendium to a weapon, it will not add it. This seems to be true for anything in the Items panel as well.

1. Have a compendium with weapon attachments (Type: Assign Consumable, Attachment?: True)
2. Log in as a Player or Trusted Player
3. Add a weapon (or uses an existing weapon) on an owned character sheet.
4. Edit the weapon on the character sheet.
5. Drag a weapon attachment from the Compendium to the weapon sheet.

The weapon attachment should attach to the weapon but it does not. This issue does not happen with the Game Master or Assistant GM roles.

Using Windows 11, Chrome 115, Foundry v11

**Comment by marvin9257** [comment]
I can confirm the issue.  It seems to be something new with v11.  I don't understand why it works for the GM but not the player.  And there is no error message to track.  @xdy do you have any suggestions?  I've trued changing dragDrop selectors to "dragDrop: [{dropSelector: '.item-sheet', dragSelector: '.item'}]," for the item-sheet, but it still doesn't work.  It is like the drop isn't triggering for the player.

**Comment by marvin9257** [comment]
seems if one overrides _canDragDrop it works?
