### ISSUE TITLE
Make it easier for others to test PR:s

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#143]
**Is your feature request related to a problem? Please describe.**
Buggy releases...

**Describe the solution you'd like**
Do builds from PR branches that can be downloaded (i.e. everything but the actual release step. Or, maybe flag as prerelease? Investigate.)

**Describe alternatives you've considered**
Make a dev branch for stabilization instead?

**Additional context**
Will require changes to the github workflows.

**Comment by jonepatr** [comment]
This would be great!

**Comment by xdy** [comment]
Probably best to go the dev branch way. And, to then protect the master branch, so all commits to it *must* come via a PR.

**Comment by xdy** [comment]
Do we want to set things up so that a new release automatically rebases (and force pushes) the development branch, or should this be a manual post-release step?
This would require anyone who uses the development branch to be aware that it's history *will* change with a new release, and that one should thus *never* keep anything locally without pushing and then just do a pull...
I haven't rebased development now, as I'm not sure what the state of the development branch is.

**Comment by xdy** [comment]
But, I probably need to rebase it from master now, if for no other reason that getting the new release workflow to it. Which just *might* create pre-releases from pushes/PR:s to development. Or it might not. Who knows. :)

Anyway, I won't do that until I've heard from you @jonepatr

**Comment by jonepatr** [comment]
Should we close this issue?
