### ISSUE TITLE
Adding Support For Token Action Hud Core

### ISSUE THREAD

**Issue by Dadrak** [xdy/twodsix-foundryvtt#1450]
Hi,

It would be nice if you could look into adding support for Token Action Hud Core : https://foundryvtt.com/packages/token-action-hud-core/

It would make the game more immersive and avoids oppening the sheet to take any kind of actions.

As always thank you for your work and have a nice day :)

**Comment by marvin9257** [comment]
I really like this idea.  I've been considering it for a few months.  The thing holding me back is that it requires a complex, separate module.  I've looked at the API a few times and I don't fully understand it.  I'll relook this week.

**Comment by Dadrak** [comment]
again this is just an idea, dont wanna force you to do something that would hinder the development of the system. But yeah the module is a huge plus, also since your system already supports Automated Animationsn, it would make your system one of the few that has both

**Comment by marvin9257** [comment]
OK, I'm not very good with the GitHub thing.  But I think you can install a test module with this link.  https://raw.githubusercontent.com/marvin9257/fvtt-token-action-hud-twodsix/main/module.json

**Comment by marvin9257** [comment]
Thanks so much for testing! The video was great to see what was happening.  How did you install it...through the url above?  I'm still having issues getting the release to update the manifest correctly.  Thanks

**Comment by Dadrak** [comment]
yes I did use the Url you have send me to install the module :)

**Comment by marvin9257** [comment]
The module is now released to Foundry Catalog https://discord.com/channels/170995199584108546/648215359895240715/1146539762283454546
Closing this issue. Thanks.
