### ISSUE TITLE
-Request- Set Finances to numbers datatype.

### ISSUE THREAD

**Issue by arkman575** [xdy/twodsix-foundryvtt#1479]
Would it be possible to convert the actor finances (cash, pension, debt, payments, livingCosts) datatypes from text to numbers? The reason for the request is to simplify the process for other modules/scripts to handle cash transactions, such as with [Monks Enhanced Journal](https://foundryvtt.com/packages/monks-enhanced-journal)'s shop system. The obvious side effect is the possibility it could alter/delete previously saved info in these spots when updating the system.

**Comment by marvin9257** [comment]
I believe these fields were setup as text to allow folks to do more freeform input, e.g. 0.5 MCr as opposed to writing the big number out.  I'll ask on discord who people's thoughts are on changing this.

**Comment by arkman575** [comment]
Totally understandable! I thought of the same reason when looking into the file structure while debugging.
