### ISSUE TITLE
Request Alternate Arrangement for Alternate Characteristics

### ISSUE THREAD

**Issue by kajishun** [xdy/twodsix-foundryvtt#1485]
**Is your feature request related to a problem? Please describe.**
No problem- just an idea. I love the hex option for characteristics. It's very on-brand. When adding 1 or 2 characteristics, they are squished to the end. When adding 3 characteristics, all turn into a small table. That is very off-brand.

**Describe the solution you'd like**
I'd love to see a 3-column option when moving from 6 to 7~9 characteristics. STR, DEX, END in the 1st column, INT, EDU, SOC in the 2nd column. And alternates in the 3rd column. Or maybe 3 rows which will mean the character window needs to grow a bit.

**Describe alternatives you've considered**
I don't know that there are any alternatives that I can try.

**Additional context**
I can't think of anything additional that is needed.

**Comment by marvin9257** [comment]
I agree that the table is not on-point, but it was the only way to fit everything in the space allowed.  The awesome graphic background was hand created.  Those background elements would need to be redrawn to add the space needed to implement this change.  So it is possible, but honestly beyond my skill to redraw it all.  UltraKev did a very nice job with the original layout.  I've just moved things as best as possible without redrawing it.

**Comment by kajishun** [comment]
Marvin (IRL Name?),

I understand. We are fortunate that my girlfriend is an accomplished,
professional graphic designer. Perhaps she'll be willing to help. Do you
happen to know what tool UltraKev used? Or the file extension of the
graphics?

Emily,

Whadya think? We'd need a few different options based on which/how many
characteristics are selected.

Cheers,
Craig

**Comment by marvin9257** [comment]
Thanks so much for the offer!  We are definitely open to contributions of all sorts.  The background images are embedded svg files.  They use to be background images, but we couldn't manipulate their colors that way.  You can find them here.
https://github.com/xdy/twodsix-foundryvtt/blob/master/static/templates/actors/parts/actor/actor-interface-bg.html
https://github.com/xdy/twodsix-foundryvtt/blob/master/static/templates/actors/parts/actor/actor-overlay-1.html
https://github.com/xdy/twodsix-foundryvtt/blob/master/static/templates/actors/parts/actor/actor-stat-1.html
https://github.com/xdy/twodsix-foundryvtt/blob/master/static/templates/actors/parts/actor/actor-stat-psi.html

You may have to extract the svg file portion as a new file to manipulate. 

One suggestion that is easier for me.  I'd rather have just one area (graphic) to use and not multiple ones.  I can fill the areas differently based on active characteristics.  I've also figured out a better way to layout the stats using inline flex.  So I can probably make a two row solution work.  It won't be the three that you'd like, but we could leave the graphics as is.
<img width="273" alt="Screenshot 2023-10-25 at 8 13 59 AM" src="https://github.com/xdy/twodsix-foundryvtt/assets/72580196/46d5b68b-e0c2-4e50-98b2-b47889fe8b17">

So eight will fit well.  I think I can get ten to fit with the rotated hexes that PSI currently uses.  Not certain as that is going to take some more programming.  So maybe hold off for now? Unless you think two row solution won't work.

**Comment by marvin9257** [comment]
here are all the characteristics with hexes
<img width="278" alt="Screenshot 2023-10-25 at 3 20 27 PM" src="https://github.com/xdy/twodsix-foundryvtt/assets/72580196/7619db61-5469-4280-8377-c42362b01556">

**Comment by marvin9257** [comment]
I'm going to keep this one open if there are updates for the graphics.

**Comment by kajishun** [comment]
Emily, what do you think? From my perspective, two rows is great. Ideally,
in my mind, the base 6 characteristics on the left side, 3 on top, 3 on
bottom. Then the options for alternate characteristics on the right side
similar to the images already posted.

Marvin, Emily may need some time as she's in the middle of another project.

**Comment by marvin9257** [comment]
Have you tried system v4.3.0 yet?  This implements the images seen above (with some slight improvements).  I don't think that we need to redo any of the graphics.  But I really appreciate the offer of help!

**Comment by kajishun** [comment]
yup, i tried it just now. i've still got the old table for all
characteristics. i tried a new actor. same. then uninstalled and
reinstalled the system. same. not sure what i'm doing wrong.

**Comment by marvin9257** [comment]
Under display settings -> actor, uncheck this option
<img width="660" alt="Screenshot 2023-11-03 at 11 23 16 AM" src="https://github.com/xdy/twodsix-foundryvtt/assets/72580196/99cff416-08ad-44ff-b66f-ee83b45117f3">

**Comment by kajishun** [comment]
/sigh&lol

yes, indeed! that did it! thanks!

btw, looks awesome!

**Comment by marvin9257** [comment]
Closing as issue resolved.
