### ISSUE TITLE
Allow Default Renaming of Basic Characteristic Short Names

### ISSUE THREAD

**Issue by kerbsy** [xdy/twodsix-foundryvtt#1521]
**Is your feature request related to a problem? Please describe.**
I am running a Sword of Cepheus variant (Westlands) that replaces SOC entirely with CHA. While I can manually change SOC to CHA on any new character I make, it'd be nice to be able to set the characteristic short names on a system level.

**Describe the solution you'd like**
Much like the settings provide an option for the names of potential alternate characteristics, I'd like to see similar fields for the main characteristics. To prevent clutter, the appearance of those fields could be determined by a checkbox or similar input.

**Describe alternatives you've considered**
An alternative solution would be to enhance the options under the "Select characteristics to display" to allow for more specific arrangements, so I could utilize something like the first five basic attributes and one alternative characteristic.
![image](https://github.com/xdy/twodsix-foundryvtt/assets/66316965/16a51cd6-a4dd-49b8-a3d2-a94f469c56a7)

**Additional context**
This feature would have use for anyone else who utilizes alternative characteristics in any version of Cepheus or Traveller, as often these may completely replace one characteristic with another, and the current settings mainly support the *increasing* of characteristics, not the replacement.

**Comment by marvin9257** [comment]
I think this change will  need to be restricted to when the actor is created.  Any modification to the actor after creation will be specific to the actor.  Any changes to the settings for short labels won't be reflected.

**Comment by kerbsy** [comment]
That was actually what I had in mind to begin with, an initializing state for the short names for new actors, not a constantly enforced state.
