### ISSUE TITLE
Journal background brightness issues with Monk's Enhanced Journal

### ISSUE THREAD

**Issue by MrZwij** [xdy/twodsix-foundryvtt#1549]
**Dark background of journal cuts off**
With the combination of Monk's Enhanced Journal ON and "Use Foundry Standard Style" OFF in twodsix settings, journals have an attractive dark background, but only for the first screen of text. Once you scroll down, the dark background gets cut off.

**To Reproduce**
1. Install Monk's Enhanced Journal
2. Open a journal entry that extends past the visible screen area. I.e. has a scroll bar.
3. Scroll down past the first screen
4. See the dark area scroll up instead of extending to the bottom of the journal entry.

**Note**
You can resize the initial window and the dark background will always fill the initial screen.

**Expected behavior**
The entire journal entry should have a dark background.

**Screenshots**
Small initial screen
![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/fdd04b31-7e12-4f7b-a2b4-9388ced64a84)

Small screen scrolled down
![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/e202f958-dabf-4e9d-b15b-59c793f3a8f8)

Large initial screen
![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/aab34ddd-559f-4696-9b62-7ad61bb80fcf)

Large screen scrolled down
![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/8f69e371-2acc-4dc4-9107-2f5845111ca3)

**Environment (please complete the following information):**
 - OS and browser: Windows 10, Edge
 - How you run Foundry: Browser
 - Foundry version: 11.315
 - System version: 4.22.0
 - Installed modules: Monk's Enhanced Journal

**Additional context**
Does not happen with Foundry Standard Style turned on.

**Comment by marvin9257** [comment]
I'm having a difficult time reproducing this issue on a Mac/Chrome.  Try setting this parameter, 
<img width="662" alt="Screenshot 2024-03-06 at 8 48 45 AM" src="https://github.com/xdy/twodsix-foundryvtt/assets/72580196/3ae53f9f-a41c-422f-b225-22c82cdbe862">

Also, maybe try chrome instead?

**Comment by MrZwij** [comment]
With just Monk's Enhanced Journal active and having changed the CSS style issue setting as you suggested, the issue is still there but it is much better. I still get the split after the first screen, but the bottom half has the default "honeycomb" background, which I like. I'd actually prefer that for the whole journal entry.

I did try this various ways and got the same result:
- In Chrome on my PC
- In the Foundry client on a different PC (Windows 10)
- In Chrome on that other PC

![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/236ca8c3-5fa5-4617-ab6d-d28d5cbe4a21)

**Comment by marvin9257** [comment]
Also check to make certain that these options fro MEJ are selected
<img width="537" alt="Screenshot 2024-03-10 at 10 54 14 AM" src="https://github.com/xdy/twodsix-foundryvtt/assets/72580196/11ef55d6-63a5-4cc7-81ba-18deda4d275e">

**Comment by marvin9257** [comment]
Even better...if you know how to use the developer tools and can post me to the css that is causing the issue that would save a lot of time. Thanks!

**Comment by MrZwij** [comment]
> Thanks...I still can't reproduce this. I'm wondering whether this is an issue with hidden html styling. Did you copy and paste this text from a source? Maybe you could export this journal and attach it to a comment. If you can't, use the html styling button and search whether there are any background changes. Sorry, this one is very strange.

I think it was a mix, but for the most part the pasting was Ctrl+Shift+V to (hopefully) clear out the styles.

I think I failed to note that these are Type > "Journal Entry", not "Text"

This is a brand-new journal entry typed by hand, created with all mods disabled except Enhanced Journal, and all settings as you asked for here https://github.com/xdy/twodsix-foundryvtt/issues/1549#issuecomment-1987276472
![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/450c9655-0648-4917-ac33-70c427249957)

![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/e34a4dfe-340e-4d04-9895-dbb039aced95)

I don't exactly know how to get the CSS for you (but happy to learn!) Is this helpful? 
![image](https://github.com/xdy/twodsix-foundryvtt/assets/12764695/0174e4a0-902e-4314-bcdf-c5908f07dac4)

When I right-click and **Copy styles** I get this: 
[editor-copy-styles.txt](https://github.com/xdy/twodsix-foundryvtt/files/14551729/editor-copy-styles.txt)

**Comment by marvin9257** [comment]
Thanks this helps a lot.  It turns out the problem was it being a journal-entry.  I can now reproduce it. A fix might take a while. Thanks!
