### ISSUE TITLE
[Request] Ability to add new range bands and armor types for CT

### ISSUE THREAD

**Issue by Not-Stabby** [xdy/twodsix-foundryvtt#1554]
**Is your feature request related to a problem? Please describe.**
When using the Classic Traveller ruleset, you can't really add any additional items, such as the ones from the CT supplements. This would require adding a new range band or armor type for each one, and if there's currently any way to do that I wasn't able to find it.

**Describe the solution you'd like**
The ability to add new items myself, assuming there isn't one already that I just don't know about.

**Describe alternatives you've considered**
An updated compendium that includes all of the items from the supplements would work too I suppose, but that seems like a lot to ask and I'm perfectly happy to just add them myself if I can.

**Additional context**
None

**Comment by marvin9257** [comment]
I understand your point here.  I struggled thinking of a good way to get the classic data into the system as it is massive tables.  There is no good way in FVTT for users to enter/edit tables like this.  Right now the tables are hard coded as large object arrays.  Are you mainly interested in B04 - mercenary?  While it would take a bit to encode, it is doable.

**Comment by marvin9257** [comment]
Well, let me think on this some.  The issue is whether to keep the current data matrix or have a custom one per weapon.  There are some advantages to the older way as currently the auto rifle fire modes work correctly in single and auto modes.

**Comment by Not-Stabby** [comment]
> Well, let me think on this some. The issue is whether to keep the current data matrix or have a custom one per weapon. There are some advantages to the older way as currently the auto rifle fire modes work correctly in single and auto modes.

Appreciate it. The CT features are really cool (Consulting those tables manually was always a massive pain) and I'd love to run it in its full glory sometime.
