### ISSUE TITLE
MGT2e Armor Modifier Stuck at Zero

### ISSUE THREAD

**Issue by jax7778** [xdy/twodsix-foundryvtt#1561]
**Before you create the bug report**
* Have you checked that this issue hasn't already been reported on https://github.com/xdy/twodsix-foundryvtt/issues?

A Similar issue has been reported for CT, (#1557 )but I am currently using "Other"  (MGT2e)

* Have you tried with all Foundry modules disabled?

Yes, issue persists 

* Have you tried to update your browser? (Do note that Safari is not supported).

Issue is Occurring on Chrome, Firefox, and Vivaldi (Chromium Base) 

**Describe the bug**
The Armor modifier seems to be stuck at zero when using the "Other" rules option, when armor is added the modifier does not increase, and cannot be increased manually (tried both in and out of edit mode). I thought I may have made a mistake when creating armor, but the same issue occurs when using armor from a built in compendium, such as CE. 

**To Reproduce**
Create a character using the "other" ruleset
attempt to add a piece of compendium armor, or create a piece of armor and add it to the character 

**Expected behavior**
I believe the armor value should increase? Or be manually editable? 

**Screenshots**
![image](https://github.com/xdy/twodsix-foundryvtt/assets/83039897/caecc928-5dc9-4392-bf45-9bd117c08e6b)

**Environment (please complete the following information):**
 - OS and browser: Client is Windows 10, Server is a Felddy Container on Azure Cloud
 - How you run Foundry: Cloud hosted Container, 
 - Foundry version: 11.315
 - System version 4.24.3
 - Installed modules: Tried with None, but I normally have 13 total. I can list if need be. 

**Additional context**
Please let me know if you need more information. 

Thanks in advance for all the work you put in for free here. I know this is not easy. Forgive me if this is something simple that I have missed.

**Comment by marvin9257** [comment]
You need to equip the armor for the protection values to appear.  Click the icon with the backpack.  Please let me know whether this works.  It seems OK on my end

<img width="791" alt="Screenshot 2024-04-29 at 2 57 30 PM" src="https://github.com/xdy/twodsix-foundryvtt/assets/72580196/c7c84a33-6fdb-4411-95f9-179cf37aa975">

**Comment by jax7778** [comment]
> You need to equip the armor for the protection values to appear. Click the icon with the backpack. Please let me know whether this works. It seems OK on my end
> 
> <img alt="Screenshot 2024-04-29 at 2 57 30 PM" width="791" src="https://private-user-images.githubusercontent.com/72580196/326569724-c7c84a33-6fdb-4411-95f9-179cf37aa975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjI0NjYsIm5iZiI6MTcxNDQyMjE2NiwicGF0aCI6Ii83MjU4MDE5Ni8zMjY1Njk3MjQtYzdjODRhMzMtNmZkYi00NDExLTk1ZjktMTc5Y2YzN2FhOTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIwMjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NGU2MmZmNWQzNDE5ZmI4YmNkZjU3YjlkYzk5ZmU5YTRmYmUyYTBmYmJmNGEzNjc2MzY2ODQ2NzI0YTg1MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I5scjC0ydMVCPLzAn8lvDAkIDIYmDRQ5KQjdN8NUVY8">



I am a moron, so sorry for bothering you.

**Comment by marvin9257** [comment]
No worries, there are a lot of subtle features to the system.  Have fun!
