### ISSUE TITLE
Request: Font-Size UI Window Scaling

### ISSUE THREAD

**Issue by alaxandir** [xdy/twodsix-foundryvtt#1565]
**Is your feature request related to a problem? Please describe.**
It is difficult to navigate the actor sheets at a font size other than 5 (Foundry Default) as configured in the Foundry System Core settings. 

The Vehicle, Animal, Robot, and Space Object sheets are already dynamically scalable so hopefully it won't be too difficult to do!

**Describe the solution you'd like**
It would be more convenient for visually impaired users if the character sheets were dynamically scalable so that the font can be all visible no matter what the size (thought at sizes of 8 or more it gets very unwieldy so I believe at least at 6 and 7 it should adjust).

Ideally the system would look at the font size used and dynamically render the actor sheet so that all content is visible, but I think the best solution is for there to be a resizable handle (either on the corner or horizontally) where Foundry will remember your preference for windows of this size and keep it that way.

**Describe alternatives you've considered**
I am uncertain what other alternatives exist other than a software magnification tool.
I looked around for other modules that make windows resizable, but they seem to only exist for Foundry UI components like the side bar, not for actual actor sheets.

**Additional context**
Font Size 6
![TqruT5CVXo](https://github.com/xdy/twodsix-foundryvtt/assets/10292802/6dac8858-097c-4ac3-83db-e6f5ad824326)
![zHL6kDWIEo](https://github.com/xdy/twodsix-foundryvtt/assets/10292802/db29c30f-ef87-4e9e-bdac-c05df7910524)

Font Size 7 (Ship)
![image](https://github.com/xdy/twodsix-foundryvtt/assets/10292802/b25e5096-91a0-4c57-a7cd-075548db3e61)

**Comment by marvin9257** [comment]
This is a great suggestion, but not one that can be easily implemented (or at least beyond my css skills).  The Traveller and Ship sheets use .svg backgrounds.  So expanding those graphics and having the areas line-up is not trivial.  I will play a bit more with this when the conversion to v12 is done.
