### ISSUE TITLE
Some minor CSS issues - only aesthetics

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1571]
**Image Browser** - "Favorite Links" and "Display Mode"-Buttons are difficult to read.

![Screenshot 2024-06-02 115310](https://github.com/xdy/twodsix-foundryvtt/assets/97696599/9193d826-3f9b-4e5c-9aad-1d8df0900d85)

**Journal Editor** - With this background, it doesn't fit to the basic design

![Screenshot 2024-06-02 120547](https://github.com/xdy/twodsix-foundryvtt/assets/97696599/cb9f879b-1230-46ac-8c2b-6c8bb53e3e90)

**Quick Insert - Search Wiget (Module)** - The white textfield with blue font is really difficult to read. I dont know if you can do something, because its a external module.

![quicksearch](https://github.com/xdy/twodsix-foundryvtt/assets/97696599/16f95252-a605-4b98-9a6f-3ea044356c1b)

**Comment by marvin9257** [comment]
As noted on Discord, I can't reproduce the JournalEntry issue.  Is there another module running that modifies JE's?  Also, I can't find the Quick Insert widget as a module.  Would you please provide a link? Thanks.

**Comment by RomKre** [comment]
https://foundryvtt.com/packages/quick-insert

**Comment by marvin9257** [comment]
As noted on Discord, the issue with JE's is selecting the TinyMCE format over Default.  Twodsix is not going to support TinyMCE any further as it is being depreciated by FVTT.
