### ISSUE TITLE
Additional Attachable Type

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1572]
**Electronics Suite or "Suite"**
for devices and options installed as standard in suits. Additionally with the option of “processing power” (like the processor-type), as many suites already have a computer integrated.
This means you don't have to attach several items but rather a single one.

At the moment, I use "Other", but it doesn't sound nice and does not support processing power.

**Additional Feature request:** Attachments supporting AE  :)

**Comment by marvin9257** [comment]
I'm am going to need to consider this further.  Attachments are, already, a hack around standard FVTT handling of items.  I'm reluctant to extend any further right now.  I keep hoping for FVTT to allow this as part of the core software.  Also, AE on attachments suffer from a similar issue.  Twodsix has a workaround, but only for items directly attached to the actor (e.g. equipment).

**Comment by marvin9257** [comment]
Is there some other functionality that would make the Suite different from a Processor attachment?  I can make another attachment type, but I want to make certain it functions correctly.
