### ISSUE TITLE
Conditional Target Modifiers from Status Effects

### ISSUE THREAD

**Issue by Vespilo** [xdy/twodsix-foundryvtt#1580]
**Is your feature request related to a problem? Please describe.**
Currently the status effects such as "In Cover" or "Targeted" that can be applied to a token are purely cosmetic, while the target modifier list that can be created in the settings is isolated from these. The suggested feature is for allowing a bridge between either to streamline some processes

**Describe the solution you'd like**
When rolling for an attack against a target with status effects (e.g. In Cover), the GM created "In Cover" target modifier should be automatically added to the active modifiers

**Describe alternatives you've considered**
Manually selecting the target modifier is working as intended, this is a pure QOL suggestion

**Additional context**
This requested feature is rule agnostic

**Comment by marvin9257** [comment]
Thanks for this suggestion.  The tricky bit will be matching the status id to the freeform text as part of the target modifiers. I haven't found a good way to do this yet.
