### ISSUE TITLE
Link Traits on actors to Target DM for attack rolls

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#1583]
as with statuses on tokens, check actor traits and link them to attack rolls

label1 +/-value1 | traitname traitlevel -> Small -2 | Small -2, 

if traitlevel is zero, then ignore it, because of troubles with traits which have no need for a level

**Comment by marvin9257** [comment]
I'm going to need to simplify this and ignore trait level.  Just match trait name. If it is a zero level trait, just don't link it. Thanks
