### ISSUE TITLE
Being able to find Twodsix by searching for "Alpha Cephei" in Foundry VTT system packages

### ISSUE THREAD

**Issue by RafaelLVX** [xdy/twodsix-foundryvtt#1627]
**Is your feature request related to a problem? Please describe.**
Currently, if you look for "Alpha Cephei" in the systems packages section of Foundry, no package will come up, although Alpha Cephei is well supported in Twodsix.

**Describe the solution you'd like**
Getting a Twodsix result when looking for Alpha Cephei in the systems search in Foundry VTT.

**Describe alternatives you've considered**
I think the issue might be that it requires the name "Alpha Cephei" right in the title of Twodsix. I don't want to highjack the title, so maybe there's some way to set up the keyword association to make it in the search results. Obviously, I'd be happy either way, with Alpha Cephei written in the Twodsix title, description, anywhere as long as it can make easier for people to find the right package.

I think maybe just adding the keywords to the description can't fix this issue. I tried searching for other words that already are in the package's description, and it didn't pick it up, otherwise I'd already have prepared a pull request to add the name Alpha Cephei somewhere.

**Additional context**
![image](https://github.com/user-attachments/assets/5375ec36-6862-409a-bf75-6c3c04cb6a4e)
![image](https://github.com/user-attachments/assets/fd099e76-7ee2-42c8-b8b1-af1457850605)

**Comment by marvin9257** [comment]
We have added publishers and products to the package description.  This is searchable online but not from the FVTT interface (probably an FVTT issue).  We don't want to change the title.  Thanks.
