### ISSUE TITLE
Time Increments Automation + Compatibility with SimpleCalendar

### ISSUE THREAD

**Issue by nearlyNonexistent** [xdy/twodsix-foundryvtt#1685]
**Is your feature request related to a problem? Please describe.**
There's no real way to automate a roll for time increments, nor is it easy to remember to tick the calendar clock forward unless it's a larger number.

**Describe the solution you'd like**
I would love if there was an optional Time Increments entry that sets how many dice to roll and what unit of measure, and then punches SimplyCalendar forward by that long if the GM clicks a button on the roll.

**Describe alternatives you've considered**
It would be simpler and still help to just automate the roll, but the incrementing the clock automatically would be very useful for the types of campaigns I run.

**Additional context**
In Cepheus, the Time Increments rule to be exact. It may be worth having this be customizable to match whichever system is being used, as Mongoose Traveller measures them differently.
https://www.orffenspace.com/cepheus-srd/skills.html

**Comment by marvin9257** [comment]
Thanks for this.  There is already some automation to roll "time frame" for a skill action if the following setting under Advanced Settings -> Rolls is enabled.

<img width="673" alt="Screenshot 2024-11-06 at 6 28 50 AM" src="https://github.com/user-attachments/assets/d6ae5669-f02d-4c5c-ae6f-55b5c75209a9">

And the bottom of the roll dialog shows time roll parameters:
<img width="396" alt="Screenshot 2024-11-06 at 6 32 17 AM" src="https://github.com/user-attachments/assets/2edf6d23-bf32-41c5-8220-fb642caddb15">

If you select a units value, the time frame roll is included with skill roll.

<img width="283" alt="Screenshot 2024-11-06 at 6 33 25 AM" src="https://github.com/user-attachments/assets/1e022a1f-5292-418f-ba97-8c9a0aaa56a3">

Are you looking for more / different automation?  We haven't implemented a going slower / faster DM as that is so situational.  It can be left for a custom DM in the roll dialog.

Once FVTT v13 is out, I'll explore whether this time frame roll can be integrated with Small Time module.  I want to wait as there might be some breaking changes that would alter the integration.

**Comment by marvin9257** [comment]
I've started at this integration.  But run into an issue with the SimpleCalendar api.  If a player rolls, the time changes only locally and does not update the other players' or the GM's calendar.  I've made a request on the simple calendar website.
