### ISSUE TITLE
Redo system settings

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#183]
**Is your feature request related to a problem? Please describe.**
Take over the system settings layout. (Maybe as a popup form that I can actually control). The current random dump of assorted settings with long descriptions isn't really fit for purpose.

**Describe the solution you'd like**
As for settings, several settings will most likely end up under a common umbrella ('Use Cepheus Light', 'Use Cepheus FTL', and if Kevin's plans go right 'Use MGT2', etc). The separate settings would still be available  - several of them are/will be handy for people that mix rules from the various variants. Like, say, me, for instance. :), but possibly hidden under a folding section or something like that.
This is also not particularly close in time as it would require taking full control of the system settings gui instead of just adding to the Foundry default one.
And, I'm lazy. :slight_smile:

**Describe alternatives you've considered**
Keep adding stuff!

**Additional context**
See this for instance: https://github.com/edzillion/blood-n-guts/blob/dev/src/module/advancedConfig.ts

**Comment by jonepatr** [comment]
Maybe a first solution would be to just have a dropdown at the top with the different systems , that would pre-populate the rest of the fields below with appropriate options for the given system. 

Currently one has to go to the docs and copy paste a bunch of options which is a bit awkward.

One can later expand on making it fancier, but this could perhaps be a good start?

**Comment by xdy** [comment]
Sure, that sounds like a useful first step!
Possibly even make it possible to save and load settings easily, though that is kind of overkill. I doubt many people would need to set up several worlds exactly the same.
