### ISSUE TITLE
Support additional characteristics

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#189]
**Is your feature request related to a problem? Please describe.**
Some variants use more/other characteristics, we should support those too.

**Describe the solution you'd like**
Other characteristics (preferably not a fixed list), should be possible to use. Maybe change to use items as characteristics?

**Describe alternatives you've considered**
Extending the characteristics list in template.json with some generically named ones (like 'extra1','extra2' etc, that you can change the display name of.

**Additional context**
See the discussion around this post for how to do it: https://discord.com/channels/170995199584108546/670336275496042502/772956369283579914

**Comment by jonepatr** [comment]
What about having a button that takes you to a popup window similar to configure audio/video or open permission configuration and there let users add rows containing the name and the short name of the new characteristics. A simpler, but less intuitive option would be having just a text field in the settings requiring the users to type something like:
`characteric-name1:short-form1,characteric-name2:short-form2`.

But my feeling as though this part belongs in the settings pane at least..

**Comment by xdy** [comment]
Also see discussion here: https://discord.com/channels/739941799820394606/739941799820394610/793134786000322580

Yeah, a popup for configuration in system settings sounds reasonable.
The characteristics would still need to be added (as EXTRA1, EXTRA2, etc, or something similar) to TWODSIX.CHARACTERISTICS in config.ts and in traveller.chararacteristics in template.json.
And, of course, I'm sure there are places where something that shouldn't be hardcoded is, but, that's what testing is for. :)

**Comment by marvin9257** [comment]
Basic functionality added in v0.11.0
