### ISSUE TITLE
Damage does not work/roll...

### ISSUE THREAD

**Issue by WildBillLives** [xdy/twodsix-foundryvtt#199]
**Describe the bug**
Damage rolls for weapons attacks do not work.

**To Reproduce**
1. Click on weapon attack button in inventory, it rolls attack - no damage is rolled.
2. Click on damage value of weapon in inventory, no roll is made.

**Expected behavior**
Last version stated "Damage rolls are now back", but they simply do not work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, latest Update.
 - Browser: Chrome
 - Version: Tested in both Foundry 0.7.6 and 0.7.7; 2d6 system version is 0.6.50

**Additional context**
Checking the console (F12) there are no error or warning messages shown when attempting to roll damage.
Also, this was tested without any other modules to make sure that no module could interfere with the results.

**Comment by xdy** [comment]
Hmm. It works for me. On a newly created world using twodsix 0.6.50 and foundry 0.7.6 I did the following:
1) Create a character, add a weapon, click the damage, which is rolled.
2) Make sure the system setting 'Automatically roll damage on skill...' is checked.
3) Add a skill to the character, connect the skill to the weapon, click the skill name, it rolls to hit, and if effect is greater than or equal to 0 (i.e. a hit), it rolls the damage (adjusted by the effect).

This works whether I have the system setting 'Show effect' turned on or not (I prefer it to be on, I never care about the total rolled, only about the effect).
I also tried a shift-click on the skill, setting different difficulties and with different to-hit modifiers, the damage was always rolled if the effect was 0 or greater.

Are you sure you had turned on the setting to 'Automatically roll damage on skill...'?

**Comment by WildBillLives** [comment]
Hello -  I just tested it out and it works fine now - I'm hosting my game on The Forge and apparently it did not update it to the latest version (I thought it was 0.6.50 but it was not). After I manually updated the system it now works fine.

Thanks for your reply - and I love the system workup, please keep improving on it like you have been!
