### ISSUE TITLE
Text unreadable in Macro windows and other areas...

### ISSUE THREAD

**Issue by WildBillLives** [xdy/twodsix-foundryvtt#211]
The entered text (both as you enter it, and after you enter it) are almost unreadable in Macros and a couple of other areas (like Modules or popups) due to the very dark background and dark text - attached screenshot shows this very well.

Thanks.

Edit - would not allow me to attach screenshot, so here is a link to a couple of examples from my Google Drive folder:

The first link shows a macro where the text is unreadable, the second link shows a module (Soundboard) where the text-based buttons do not show text at all, making all the buttons unreadable and the module almost useless:

https://drive.google.com/file/d/1HhtOx4BtdoT0XLXndEtOXyief032mHnz/view?usp=sharing

https://drive.google.com/file/d/1bak321blNBxzwgnhcbSCIcUd3rkEZM_W/view?usp=sharing

**Comment by WildBillLives** [comment]
I would actually switch this to a **bug,** not a feature, since it does severely affect the game and the use of macros and other modules becomes almost impossible.

**Comment by xdy** [comment]
Can you take a look at this @UltraKev ?

**Comment by WildBillLives** [comment]
I just disabled all modules that I was using and the text issue above goes away, so it is obviously a module conflict. 
I will re-add modules until I find the one that is causing the issue and make a note of it here. 

Thanks!
