### ISSUE TITLE
Request a popup/option to add a modifier to characteristic/ skill checks and attack rolls...

### ISSUE THREAD

**Issue by WildBillLives** [xdy/twodsix-foundryvtt#213]
My players (along with myself) would VERY much appreciate it if there were a popup (after you click to roll a char/skill/attack check) that would allow you to enter a modifier for the check/roll. As it is right now, you either have to open the skill and/or attack and change the difficulty (which would not allow for odd number modifiers anyway) or add the modifier manually to the check after the fact. 

This would also make the "Auto roll damage if you succeed"  option much more useful, since right now if you have a modifier to the roll you cannot add it and thus the effect value actually rolled will be incorrect when it triggers the auto-damage roll.

Thanks.

**Comment by xdy** [comment]
Your wish is granted. :)
Or, rather, something very much like that feature exists already. Try shift-clicking the skill/weapon/characteristic. That gives you a dialog where you can change difficulty, set advantage/disadvantage, add any modifier, etc.
See this pinned post in #general on the discord
https://discord.com/channels/739941799820394606/739941799820394610/765225313000357888

**Comment by WildBillLives** [comment]
Thanks! Me nor my players had no idea that was possible. I clicked on the discord link you posted but it did not take me to a discord channel...can you give me an invite or something -I would love to join the discord. my discord username is WildBillLives#5901

**Comment by xdy** [comment]
Oh, sorry, I thought I recognized the user name from our discord. :)
Here's the invite link:
https://discord.gg/KUAwPrj
