### ISSUE TITLE
Add discord integration to releases

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#219]
**Is your feature request related to a problem? Please describe.**
I'm too lazy to post announcements...

**Describe the solution you'd like**
When I do a release, an announcement should be posted to #announcements on the twodsix discord.

**Describe alternatives you've considered**
Don't be lazy?

**Additional context**
See this: https://github.com/DiscordHooks/github-actions-discord-webhook

**Comment by jonepatr** [comment]
Fixed
