### ISSUE TITLE
Damage doesn't work for unlinked tokens

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#232]
**Describe the bug**
On an unlinked token, do damage, watch nothing happen.

**To Reproduce**
See above.

**Expected behavior**
Damage should happen on this token, not on any other unlinked copies, or on the base actor for that matter.

**Additional context**
Might have something to do with the code using actor.update, but, checking if linked and if not using token.update didn't help.
Haven't seen any other systems having problems, so not sure what's going on.

**Comment by xdy** [comment]
It might be that what needs to be done is to shift things around. Make Hits the actual hitpoints, and have damage/healing to that affect the characteristics. Hits would be recalculated from whatever the current values are when the characteristic *value* changes, never otherwise. This would probably also necessitate making the current damage edit fields non-editable.

**Comment by jonepatr** [comment]
I'm having a look at this. Have gotten a little bit closer. Seems like an unlinked token should be handled differently than a linked token, and there is the token.data.actorData field in an unlinked token which has priority over the original actor data.
