### ISSUE TITLE
Go through the item templates in template.json and make sure all fields in there are editable in the editor for that item type.

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#251]
**Is your feature request related to a problem? Please describe.**
Not all fields are user visible. Even if they are not currently supported by the system, they should be reachable.

**Describe the solution you'd like**
For all fields in the template to be user visible, if appropriate. Some fields should probably default to not visible but have a system setting to start showing them.

**Describe alternatives you've considered**
Ignore them.
Remove the fields. (Which may actually be appropriate for some fields, there could well be useless crud there.)

**Additional context**
n/a

**Comment by jonepatr** [comment]
enemies and allies should be removed from the template.json

**Comment by jonepatr** [comment]
shipstats and reqpower maybe needs to be removed

**Comment by marvin9257** [comment]
I don't think we should proceed with this action.  For example, there is a "system.conditions" that tracks the effects of system applied conditions.  Also, shipstats is used for several calc/summary fields on ship sheet now.
