### ISSUE TITLE
Add --rule 'no-trailing-spaces: error' to eslint

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#257]
**Is your feature request related to a problem? Please describe.**
Unwanted whitespaces should be detected and fixed during linting

**Describe the solution you'd like**
add --rule 'no-trailing-spaces: error' in package.json

**Describe alternatives you've considered**

**Additional context**

**Comment by xdy** [comment]
Fixed with https://github.com/xdy/twodsix-foundryvtt/commit/e49c61c4115c8cf3c76d8ed9aa31d4484ba42217 (I added it to the .eslintrc.yml instead, that way the IDE has a chance to know about it. Might need a plugin though.
