### ISSUE TITLE
Item windows should be large enough to show all fields

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#264]
**Is your feature request related to a problem? Please describe.**
Mostly annoyance

**Describe the solution you'd like**
When opening or creating an item, the item window height should adapt to the content, if the screen resolution is large enough.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by jonepatr** [comment]
I'll have a look at this one!

**Comment by xdy** [comment]
All yours!
