### ISSUE TITLE
Switching the behavior of shift-clicking and clicking on a skill

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#267]
**Is your feature request related to a problem? Please describe.**
Currently it is hard to discover by just using the interface how to get the dice roller which let's you modify difficulty (and more) of the roll. One has to turn to the documentation to find this.

**Describe the solution you'd like**
Switching the behavior of the regular click and shift-click for skill checks. However, a flag should exist in the settings menu which let's you revert to the current behavior. Furthermore, when hovering over the skill test the title attribute for the link should state what happens when you click and also contain a note about shift-clicking. Something like "Rolls for damage. Shift-clicking rolls applying no modifier and assumes a difficulty of 8" (and then of course if the inverse flag is set this should be inverted)

**Describe alternatives you've considered**
Providing documentation inside foundry. However, i think it's better to not have important functionality hidden in the ui.

**Additional context**

**Comment by xdy** [comment]
I agree with all of the above. Affordance trumps documentation every time.
Even though I sometimes claim that "If it can't be done on a VT52 it should be illegal!" :)
