### ISSUE TITLE
Dragging entities into text fields in the character sheet should work the same way as journal entries.

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#268]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to drag an entity into a text field of the character sheet. For example, adding an NPC as ally and having them linked from the character sheet.

**Describe the solution you'd like**
I should be able to drag and drop an entity into a text field and have it become a reference to that entity.  

**Describe alternatives you've considered**

**Additional context**

**Comment by xdy** [comment]
Yeah, if we don't merge them into one field as per #269, this would be *real* handy. We would need to support having several of each type though. (As in, most likely, store the id and show the name as a link I guess?)
The same would be very useful for ship crew as well.

**Comment by marvin9257** [comment]
This is now possible to drop an actor onto an active ProseMirror window (it must be in edit mode).
