### ISSUE TITLE
Missing rival field in the character sheet

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#269]
**Is your feature request related to a problem? Please describe.**
There is currently no rival field in the character sheet

**Describe the solution you'd like**
Adding one

**Describe alternatives you've considered**
Having one larger text field for all types of contacts.

**Additional context**
I'm not sure if rivals are part of all variants of the game. I know mgt2 and ce has rivals, not sure about the others. If there  is a difference I guess a system settings flag could be used.

**Comment by xdy** [comment]
My personal preference is for one text field for all types of contacts (ally/enemy/rival/whatever). Just a place to note down relations to npcs. That would require a migration, and character sheet changes.
What is your opinion @UltraKev ?

**Comment by xdy** [comment]
Actually, after thinking a bit more on it, the two (#268, #269) do not need to conflict. A large text field with the possibility of character links, that one can drag into the text field.
