### ISSUE TITLE
Implement Traits

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#272]
**Is your feature request related to a problem? Please describe.**
Needed to handle both alien species and things like https://www.drivethrurpg.com/product/262129/Cepheus-Light-Traits (which will be included by default in the next edition of Cepheus Light).
JOAT can also be handled this way, see #57 
Basically, if something is innate to a character, but is neither a skill nor a psionic power, it should probably be a trait.

**Describe the solution you'd like**
Add a new item type 'trait', that would have 'key','name','level','description' to start with. Then add them to the character sheet (probably a new tab, possibly a new list below skills).

This is intended to support all 'this character breaks a particular rule' situations.
In the long run these (along with items) should also have Active Effects.

**Describe alternatives you've considered**
Keep adding ad hoc comments in Notes.

**Additional context**
https://www.orffenspace.com/cepheus-srd/character-creation.html
https://www.drivethrurpg.com/product/262129/Cepheus-Light-Traits

**Comment by jonepatr** [comment]
Could this be a way to handle weapon traits as well?

**Comment by xdy** [comment]
That is indeed what the "traits":[] line in gearTemplate in template.json was intended for, though it's never been used.
And, now that I look at it, CL has weapon aspects, not traits, so I guess the "traits" on gear should be removed and replaced with "aspects" instead. For CL rate of fire should be removed, and replaced with looking at 'level' in the 'AUTO' aspect, if any.
I'll make an issue for the above.

**Comment by jonepatr** [comment]
Would  this be a good place to use the active effects?

**Comment by marvin9257** [comment]
We can close this one, I think.
