### ISSUE TITLE
Investigate what supporting Active Effects could bring to Twodsix

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#273]
**Is your feature request related to a problem? Please describe.**
Not sure. That I don't know what it would add, and how much effort it would be, I guess.
Could definitely be used for various items and traits (e.g. cybernetic parts that add strength, etc)

**Describe the solution you'd like**
Research it, implement it for something, add plans for further uses.

**Describe alternatives you've considered**
Ignore it.

**Additional context**
https://docs.google.com/document/d/1DuZaIFVq0YulDOvpahrfhZ6dK7LuclIRlGOtT0BIYEo/edit#
Other than dnd5e I know SWADE (https://gitlab.com/peginc/swade) and WFRP4 (https://github.com/moo-man/WFRP4e-FoundryVTT/) uses them.
Relates to #272 and #57

**Comment by marvin9257** [comment]
Active Effects have been added to the system - for better or worse
