### ISSUE TITLE
Support import of characters from 1001 characters

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#3]
**Is your feature request related to a problem? Please describe.**
I want to be able to generate CE actors easily. http://members.ozemail.com.au/~jonoreita/SupplementOne/Cepheus_Engine_1001_characters.html generates a bunch of random ones - with some configurability, and outputs them in a fairly standard  (UPP/UCF) format.

**Describe the solution you'd like**
I want to be able to paste one or more characters and make them into actors.

**Describe alternatives you've considered**
Well, I could start with a form for entering characters field by field, but, meh.

**Additional context**
A way to convert skillsmight be worthwhile. (e.g. for CE > CEL: "*Cepheus Light skills are somewhat different than the
ones included in the Cepheus Engine core rules but are easily compatible. Most notably, Repair is the combination of
Electronics and Mechanics; Admin subsumes the Advocate skill; Carousing subsumes the Gambling skill; Piloting
subsumes the Navigation skill; and Deception is roughly equivalent to certain uses of Carousing and Streetwise in the core
rules.*" How to handle Repair and Deception? I guess split evenly, starting with a random selection.)
Should probably be a module, with other modules for importing from other generators.
It *might* be worth doing this by simply including 1001 characters *in* the module. Don't know what the license situation for that would be.

Should (in separate issues) set up support for importing from other random character builders (for various cepheus-compatible systems) too, such as:
http://www.batintheattic.com/traveller/
https://travellertools.azurewebsites.net/Home/Character?minAge=&maxAge=&firstAssignment=&finalCareer=&finalAssignment=

And animal generators like:
https://travellertools.azurewebsites.net/Home/Animals?terrainType=&animalType=
https://peterssoftwareprojects.com/2018/06/21/traveller-animal-generator/
http://www.neuzd.org/traveller/travellergen.php?i=aen&t=0
https://travellertools.azurewebsites.net/Home/AnimalEncounters?terrainType=&animalClass=

**Comment by xdy** [comment]
There are some remnants of a simple UCF sheet and thoroughly broken import code that might be worth resurrecting. Search for UCF.

**Comment by marvin9257** [comment]
Can we close this one based on the macro implementation? [https://github.com/xdy/twodsix-foundryvtt/blob/master/user_macros/NPC%20Parsers/Parser%20for%20CE%201001%20Characters.js](here)

**Comment by xdy** [comment]
I agree, your macros cover this issue nicely!
