### ISSUE TITLE
Show only limited information on character sheet when user has "limited" permission

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#334]
**Is your feature request related to a problem? Please describe.**
I would like to show my players NPCs without showing their stats and various information about them.

**Describe the solution you'd like**
Currently it seems like the "observable" and "limited" permissions shows the same information about a character. I think it would be nice if the "limited" permission only showed picture, name (perhaps there even could be a separate "display name") gender, age, and the description field.

**Describe alternatives you've considered**
Having NPCs as journal entries

**Additional context**
-

**Comment by jonepatr** [comment]
looking at dnd5e, they only show name and image. Should we also only show those?

**Comment by xdy** [comment]
Looks good, merging to master!
