### ISSUE TITLE
The ship sheet needs localization support

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#337]
**Is your feature request related to a problem? Please describe.**
The strings are currently hardcoded, so it can't be translated.

**Describe the solution you'd like**
Use {{localize}}//game.i18n.localize like everywhere else.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by marvin9257** [comment]
I believe this has been fixed in the latest version!
