### ISSUE TITLE
Request for a "Move" Attribute...

### ISSUE THREAD

**Issue by WildBillLives** [xdy/twodsix-foundryvtt#361]
**Is your feature request related to a problem? Please describe.**
No, just something that would be useful.

**Describe the solution you'd like**
Add an attribute that would hold a numeric value for the actors base Movement rate.

**Describe alternatives you've considered**
Not sure what alternate would work, as an actual game attribute would be required for movement to be used with certain modules such as "Drag Movement" or any other module that makes use of a movement rate.

**Additional context**
None really.

**Comment by xdy** [comment]
Good idea. The biggest problem is figuring out where in the gui to fit it in. :)
