### ISSUE TITLE
Separate initiative formula into traveller / ship formulas

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#380]
**Is your feature request related to a problem? Please describe.**
The formulas for initiative differs for travellers and ships, so when having  ship combat initiative has to be rolled manually

**Describe the solution you'd like**
Add a field  in the settings for "ship initiative formula"

**Describe alternatives you've considered**
Just  adding it manually

**Additional context**
-

**Comment by xdy** [comment]
Each actor type should probably have it's own initiative formula setting.
Some details on what rules can be implemented

Cepheus Engine
The default formula for ships should probably simply be 2d6. Fully implementing the rules from Cepheus Engine (https://www.orffenspace.com/cepheus-srd/space-combat.html) while certainly possible doesn't really seem worth it.
```
Initiative

Each ship in an engagement rolls 2D6 to determine their starting Initiative score. The ship with a greater Thrust score gains a +1 DM to its roll.

The Captain of each vessel (or each fleet, if more than one ship is involved on each side) may a Tactics check. The Effect is added to the Initiative of the vessel (or fleet). 
```

Cepheus Light and Cepheus Faster Than Light space combat doesn't have the concept of initiative, instead one rolls for Advantage each round, which has a direct game effect as a DM on to-hit rolls depending on how well you rolled.
Could be handled rolling 2d6+captain's piloting + acceleration as a pseudo-initiative, but displaying the DM as the initiative. Possibly a good idea to set this modifier on all ship based weapon attacks. (But, probably not worth doing until we actually link actors to ships.)
For now, I think setting Initiative to 0 for CL and CFTL ships is good enough. It's as wrong as any other value. :)
Quoting:
```
ADVANTAGE
There is no initiative or range to track in space combat. Each space combat round, all participating ships' pilots throw 2D +
Piloting + the ship's maneuver drive acceleration. The winner of this opposed throw has Advantage and may attack with
the following modifiers:
Effect | DM
-- | --
0 | DM-2
1 or 2 | DM-1
3 or 4 | DM+0
5+ | DM+1
The loser of the Advantage throw suffers DM-3 to attack anyone with a higher Advantage number than them, for the round. This penalty applies to turrets and bays. Weapons in fixed mounts cannot attack without Advantage. Note that two vessels that have the same result for their Advantage throw can still attack each other, albeit at DM-2 to their attack throws.
```

Cepheus Atom doesn't even have space combat rules.
