### ISSUE TITLE
Opposed rolls

### ISSUE THREAD

**Issue by waynetrav** [xdy/twodsix-foundryvtt#389]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. 

**Describe the solution you'd like**
Opposed rolls between players or a single player and the referee. Perhaps a pop up where the character in question are selected, their skills/attributes are selected and then a roll is made with the total effect visible. This would effectively be an equation--(player 1 skill+attribute=effect)-(player2 skill + attribute=effect) = net result with an awarded victor. 

**Describe alternatives you've considered**
This could be a macro too, perhaps. 

**Additional context**
Page 6, CE engine rules "If two characters are opposing each other directly in a task, then the character who obtains the highest Effect wins. For ties on opposed checks, the character with the highest relevant characteristic score wins. If the characters tie on characteristic scores, they reroll."

**Comment by xdy** [comment]
Perhaps by default split the 'sides' such that all Friendly actors are on one side, and all Hostile on the other, with Neutrals listed in a separate box below. One can then drag the actors to the proper box.
Or, maybe better, all player owned in one box, and everyone else in the other.

**Comment by jonepatr** [comment]
What about if another actor/token is targeted then both will receive a skill roll dialog and when both have rolled it will tell who won the opposed roll?
