### ISSUE TITLE
Task chains

### ISSUE THREAD

**Issue by waynetrav** [xdy/twodsix-foundryvtt#393]
**Is your feature request related to a problem? Please describe.**
This is just a nice thing to have, not related to any problems. 

**Describe the solution you'd like**
For players to have an interlinked series of rolls for one final effect.

**Describe alternatives you've considered**
The ol' eyeball. 

**Additional context**
MGT rulebook, 2nd edition, page 60: "Often, Traveller will find themselves performing a series of interlinked tasks or working as a group. Finding a buyer for a cargo of illegal goods, for example, calls for a Streetwise check to find a fence, then a Broker check to negotiate a price. The result of the streetwise check could conceivably influence the quality and competence of the fence, who will affect the broker check. 

Alternatively, when coming up with a plan to attack a fortress, the Travellers would being with a recon check to scope the place out, then a Tactics check to find weak spots in its defenses, then Stealth and Electronics rolls to get past the security system. The quality of information gleaned from the Recon check will certainly have an impact on the tactics the Travellers choose to adopt, and this in turn will make their Stealth checks easier or harder, and so on.

When tasks are linked together like this they are called task chains and the result of one check can give a DM to the next -- for better or worse. The DM gleaned from one check and then applied to the next is shown the Task Chain table."

**Comment by xdy** [comment]
We can't support non-OGL rules (specifically, we don't have the license for MGT2) and I haven't been able to find anything like this rule in the various Cepheus games, so I'm closing this issue.
