### ISSUE TITLE
Make it possible to choose where items are

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#394]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to show in the character sheet what the character actually has on them and what they owned, but for example left in  the ship.

**Describe the solution you'd like**
For each item being able to specify where the item is located. If it's located in a place other than the inventory it could be grayed out (bonus thing would be to have a checkbox on the character sheet letting you hide all items not  currently carried). It might be good to have a place on the character sheet where it says where a players owned but not carried items are located. 

**Describe alternatives you've considered**
Having a simple equip/unequip checkbox for each item.

**Additional context**

**Comment by xdy** [comment]
The current template.json has some support for the alternative, the equip/unequip checkbox should change the actor item's data.equipped.weight, setting it to the item's data.weight (for equipping) or 0 for unequipping. (This value then presumably to be used for handling encumbrance.)
For the full solution, taking a good look at what https://github.com/syl3r86/inventory-plus does seems like a good idea. (There are other modules that add recursive containers, but I feel that is *way* too much hassle.) And changing the template.json and gui to support this, of course.

**Comment by jonepatr** [comment]
Maybe starting with a simple equip/unequip thing is best? I agree that a similar solution to intentory-plus would be nice, but perhaps that can be pushed into the future. 

I think if we want to implement traits for items/actors then equip/unequip is quite important, as if we use active effects for armors for example, then they will automatically add armor to the actor, so there has to be a way for the user to say what things are equipped and what is only owned by the actor, so that we only apply the effects of the items that are equipped

**Comment by marvin9257** [comment]
I believe this issue was closed with release #686
