### ISSUE TITLE
New ESLint NPM Module - `@typhonjs-fvtt/eslint-foundry.js` deprecated

### ISSUE THREAD

**Issue by typhonrt** [xdy/twodsix-foundryvtt#397]
Hiya... Just a courtesy call to mention that `@typhonjs-fvtt/eslint-foundry.js` has been deprecated and the new NPM module is [@typhonjs-fvtt/eslint-config-foundry.js](https://www.npmjs.com/package/@typhonjs-fvtt/eslint-config-foundry.js). The reason for the deprecation is that to enable the module as a [shareable ESLint config](https://eslint.org/docs/developer-guide/shareable-configs) required a name change for ESLint naming conventions. 

The new module has updated support for 0.7.8 to 0.8.0 Foundry VTT releases and also now features a difference set / exclusion set config of global variables dropped / now undeclared between the 0.7.9 to 0.8.0 versions to use for migration.

Happy coding and good luck with your module / system & Foundry VTT migration to 0.8.x and beyond!

**Comment by xdy** [comment]
Thanks!
