### ISSUE TITLE
Make Twodsix work with Foundry VTT 0.8

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#421]
**Is your feature request related to a problem? Please describe.**
Foundry 0.8 has quite a few big changes that will most likely require code changes in Twodsix.

**Describe the solution you'd like**
Sometime before Foundry 0.8 goes stable (0.8.5 or so), Twodsix should support it. Serious work on it is probably not worth starting until 0.8.2 or so, but some exploration before that would be useful.
Might be worth waiting until the foundry-vtt-types starts working on Foundry 0.8

**Describe alternatives you've considered**
Embrace Irrelevance!

**Additional context**
Installing Foundry 0.8 and trying to build and run Twodsix should give some indication on how much work is required.
See https://foundryvtt.com/releases/0.8.0 and the various #080-something channels in the Foundry discord as well as the #foundryvtt-080-research in the league discord.

**Comment by jonepatr** [comment]
I'll take a stab at getting consumables to work, right now they are acting up when being created on an item

**Comment by jonepatr** [comment]
When rolling the following warning comes up: Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.

This should be looked at and decided if we want to do async or not.

**Comment by jonepatr** [comment]
it does not work to roll for damage

**Comment by jonepatr** [comment]
Rolling initiative in combat does not work

**Comment by jonepatr** [comment]
drag-and-drop of items onto character sheet does not work

**Comment by jonepatr** [comment]
drag-and-dropping compendium items/skills seems to work. But dropping compendium items generates the following warning: `You are calling CompendiumCollection#getEntity which has been renamed to CompendiumCollection#getDocument. Support will be removed in 0.9.0.`

While dropping compendium skills generates the following warning: `You are calling CompendiumCollection#getEntity which has been renamed to CompendiumCollection#getDocument. Support will be removed in 0.9.0.`

**Comment by jonepatr** [comment]
assigning stats to a ship does not work

**Comment by jonepatr** [comment]
After adding consumables to an item, and reloading the page, there is an issue with preparing the items belonging to an actor

**Comment by xdy** [comment]
Speed up build system by turning on esbuild (takes dev builds from ~5 seconds to ~800 milliseconds)
This *might* make dynamic imports possible (which could be useful for fixing the migration system), see https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars. I left a todo in migration.ts

**Comment by xdy** [comment]
Dragging damage to an actor doesn't seem to work.

**Comment by xdy** [comment]
Handling damage manually by editing the damage fields sort of works, it calculates the new modifier, but allows one to take more damage than possible. (E.g. with str 7 one should only be able to take 7 str damage, but one can enter any value).

**Comment by xdy** [comment]
After having created an actor, and closed it, I can no longer open it. Nor can I open any other actor, whether newly created or from a compendium. Neither refreshing nor exiting and reentering the world makes a difference. No errors in the console.
If I create a new world, I can create actors in that world. I *think* it has something to do with settings, as after creating several characters I broke actor creation in that world by playing with the settings.
(Not working on this right now, just noting it).

**Comment by jonepatr** [comment]
> Dragging damage to an actor doesn't seem to work.
> (Not working on this right now, just noting it).

Strange, I specifically tested this and it worked for me.

**Comment by xdy** [comment]
Just retested without my changes to the build system on a new character on a new world and still get the same behaviour. (On windows, using firefox, foundry 0.8.5) 
So, doesn't seem to be a missing hook or that sort of thing (the hooks are visible in the bundle).

**Comment by xdy** [comment]
Tested after latest commit, dragging damage works now!

**Comment by xdy** [comment]
An example of a world with characters I can no longer open.
[t3.zip](https://github.com/xdy/twodsix-foundryvtt/files/6528058/t3.zip)

**Comment by xdy** [comment]
And, the above problem should be fixed, was a missing file in templatePaths.

**Comment by xdy** [comment]
Just realized I never closed this issue...
