### ISSUE TITLE
Using hotbar macro does not bring up damage dialog as expected

### ISSUE THREAD

**Issue by sheck** [xdy/twodsix-foundryvtt#472]
**Describe the bug**
When using a hotbar macro for weapon rolling (after dragging it to the hotbar) the damage does not show up automatically as it would when rolling from the sheet.

**To Reproduce**
1. Enable "Automatically roll damage on skill rolls [...]" in system settings
2. Add a weapon with damage
3. From the actor sheet, roll it until a positive effect is achieved
4. See the damage dialog appear
5. Drag that weapon to a hotbar slot
6. Roll by clicking the hotbar icon or the keyboard shortcut until a positive effect is achieved

**Expected behavior**
The damage dialog appears as it did in step 4

**Actual behavior**
The damage dialog box _does not_ appear

**Environment (please complete the following information):**
 - OS and browser: macOS 11.2.3
 - How you run Foundry: Foundry Client
 - Foundry version: 0.7.9
 - System version: 0.7.28
 - Installed modules: twodsix, collapsible compendiums, Zoom/Pan Options

**Comment by marvin9257** [comment]
Perhaps inelegant and probably might break easily, but I think this macro will get you part of the way there . As GM the actor needs to be selected to work.  Also drag and drop as normal to create the macro and to find the right ID (the weird string in the quotation marks).  Replace dragged macro with below (replace 5ZIasbikS8nE8PAL with what the original macro defined in the quotes).

let attacker = null;
if(token !== undefined){
    attacker = token.actor;
    shoot(attacker);
}

async function shoot(attacker)
{
    const weapon = await attacker.items.find(item => item._id == "5ZIasbikS8nE8PAL");
    weapon.performAttack("", true, 1);
}

**Comment by marvin9257** [comment]
I think the real fix would be to replace line 21 in the rollItemMacro.ts file with something like:

if(item.data.type!="weapon") {
          await item.skillRoll(false);
      } else {
        await item.performAttack("", true, 1)
      }
