### ISSUE TITLE
Null consumable item created when pulling weapon from compendium

### ISSUE THREAD

**Issue by xevus11** [xdy/twodsix-foundryvtt#490]
![Capture](https://user-images.githubusercontent.com/7450396/118568383-b7d8d780-b745-11eb-94fa-9d281d53c0f6.PNG)
When an item added with a consumable is added to the compendium, any subsequent actor that item is assigned to instead has a consumable with a null reference. This consumable cannot be edited or removed from the actor.

**Comment by xdy** [comment]
The change above is in, so closing this issue.
