### ISSUE TITLE
Macros not created correctly on drag and drop

### ISSUE THREAD

**Issue by marvin9257** [xdy/twodsix-foundryvtt#511]
**Before you create the bug report**
* Have you checked that this issue hasn't already been reported on https://github.com/xdy/twodsix-foundryvtt/issues?
* Have you tried with all Foundry modules disabled? yes

* Have you tried to update your browser? (Do note that Safari is not supported).

**Describe the bug**
When dragging and dropping an item into the macro bar, the macro script isn't created correctly.
game.twodsix.rollItemMacro("undefined");

**To Reproduce**
1. drag a item/weapon from player sheet to macro bar
2. edit macro to see script

**Expected behavior**
instead of "undefined", there should be an item id code between the quotation marks

**Screenshots**

**Environment (please complete the following information):**
 - OS and browser: [e.g. 'Windows 10' or 'Ubuntu 20.04'] MacOS
 - How you run Foundry [e.g. 'Foundry client' or 'Chrome'] node server
 - Foundry version [e.g. 0.7.9] 0.8.6
 - System version [e.g. 0.6.82] 30.8.0
 - Installed modules compendium folders, libWrapper, codeMirror

**Additional context**
I think it has to do with this line in createItemMacro().  
const command = `game.twodsix.rollItemMacro("${item.id ? item.id : item.data.id}");`;

I think it should be
const command = `game.twodsix.rollItemMacro("${item.id ? item.id : item.data._id}");`;
item.data._id is valid id code under 0.8.6.

<img width="1038" alt="Screen Shot 2021-06-04 at 4 31 40 PM" src="https://user-images.githubusercontent.com/72580196/120865106-00203400-c553-11eb-983b-45e2f6ffb64a.png">

**Comment by marvin9257** [comment]
I can confirm that the changes works locally on my system.

**Comment by marvin9257** [comment]
OK, I think the confusion is that getItemDataFromDropData() returns item.data and not an item.  So what is passed to createItemMacro is not an item but item.data. I think that is why there is no item.id.

**Comment by xdy** [comment]
The change above is in, so closing this issue.
