### ISSUE TITLE
UI options

### ISSUE THREAD

**Issue by sirkerry** [xdy/twodsix-foundryvtt#512]
**Is your feature request related to a problem? Please describe.**
Nope, other than taste.

**Describe the solution you'd like**
I'd like to be able to have different UIs available for this ruleset, the one you have is fine for lots of sci-fi stuff but I like to use the 2d6 rules to run fantasy, western, and 1930s pulp games - and option to use the regular default Foundry VTT UI would be great.

**Describe alternatives you've considered**
Just don't what to be limited to genre specific UI, something genre-neutral like the default FoundryVTT UI would be best as the default, with options for the sci-fi one you have now and maybe some other genre focused ones in the future (but I'd be happy with just the generic genre-neutral one that most of the Foundry VTT systems already use).

**Additional context**
nope

**Comment by marvin9257** [comment]
This has been addressed with release 0.10.0
