### ISSUE TITLE
Discord Invite Link Expired

### ISSUE THREAD

**Issue by James-Firth** [xdy/twodsix-foundryvtt#519]
**Describe the bug**
The link in the README is invalid and gives an error.

**To Reproduce**
1. Go to the README.md
2. Click on the discord link ( https://discord.gg/VNFUvjv )
3. See error on url  ( https://discord.com/invite/VNFUvjv )

**Expected behavior**
Be invited to the discord server

**Screenshots**
![image](https://user-images.githubusercontent.com/485809/121755874-ec8a4580-cadd-11eb-8763-b1202488f520.png)

**Environment (please complete the following information):**
 - MacOS, Firefox

**Comment by xdy** [comment]
Oops. Fixed. Thank you!
