### ISSUE TITLE
Unlinked actor status change to deadEffect causes error

### ISSUE THREAD

**Issue by marvin9257** [xdy/twodsix-foundryvtt#531]
**Before you create the bug report**
* Have you checked that this issue hasn't already been reported on https://github.com/xdy/twodsix-foundryvtt/issues?
* Have you tried with all Foundry modules disabled?
* Have you tried to update your browser? (Do note that Safari is not supported).

**Describe the bug**
When causing enough damage to an unlinked actor though dragging a damage chat item to reduce the actor to 0 health, an error is reported:

<img width="573" alt="Screen Shot 2021-06-25 at 3 53 08 PM" src="https://user-images.githubusercontent.com/72580196/123484166-8a493e80-d5cd-11eb-90ad-829fa54dce36.png">

**To Reproduce**
Drag enough damage to an unlinked actor to cause death

**Expected behavior**
Death effect icon appears on actor token

**Screenshots**

**Environment (please complete the following information):**
 - OS and browser: MacOS
 - How you run Foundry: NodeJS
 - Foundry version: 0.8.8
 - System version: 2021_02_10_10_20
 - Installed modules: Code Mirror, Compendium Folders, libWrapper

**Additional context**
It appears to be a problem with line 122 of actorDamage.ts:
`this.actor.token.toggleEffect(deadEffect, {active: true});`

It think it should be
`this.actor.token.data.document._object.toggleEffect(deadEffect, {active: true});`
but this seems a bit convoluted.

**Comment by marvin9257** [comment]
There seems to be some conflict when toggling the effect and updating the actor.  The code works, but on refresh right after a target is toggled with dead icon the applied damage is undone.  If the toggleEffect code is commented out, the damage sticks after refresh.

**Comment by marvin9257** [comment]
An update - this seems to be a problem with the damage dialog.  If one shift-drops damage the damage sticks on refresh.

**Comment by marvin9257** [comment]
It is a sync problem.  Made the function async and await changes seems to fix issue.

**Comment by xdy** [comment]
The fix above is in, so closing this issue.
