### ISSUE TITLE
Support jack of all trades (i.e. different base value for untrained skills)

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#57]
**Is your feature request related to a problem? Please describe.**
JOAT is a 'skill' that adjusts the base value of untrained skills for a character. Level 0 does nothing, level 3 is maximum skill level.

**Describe the solution you'd like**
When you take a level of JOAT, your base value for untrained skills should change.

**Describe alternatives you've considered**
Just remember it. Every time.
Just adjust the value of all untrained skills.

**Additional context**
https://www.orffenspace.com/cepheus-srd/skills.html#jack-of-all-trades

**Comment by xdy** [comment]
This might be best handled as a Trait that changes the 'minimum skill level' on the character (i.e. the skill level a new skill gets added at.)
That is, use the same item type as racial traits etc, which haven't been added yet.

**Comment by xdy** [comment]
Jack of All Trades isn't particularly well supported.
One setting is per-client (i.e. each logged in user can set it), "The value that is used for untrained skills.", Change this to match the character's level of the 'Jack of All Trades' (JOAT) skill. If you have JOAT 1, set the value to -2, etc.
As long as each player only has one character this works fairly well.
Of course, it fails horribly if a player has several characters with different levels of Jack of all trades. (As there is only a setting per player rather than per character).

This setting needs to be removed and a proper solution implemented.

**Comment by jonepatr** [comment]
Would a solution be to just have a permanent skill as part of the character sheet for jack of all trades, which then in turn modifies all untrained skill rolls?

**Comment by xdy** [comment]
My thought on this was to add a new item type 'trait', that would have 'key','name','level','description' to start with. Then add them to the character sheet (probably a new tab, possibly a new list below skills).
Then the code that currently sets the unskilled penalty would check for the 'JOAT' trait, check it's level, and set the penalty.

The point of doing it via traits is traits would also be used to support all other 'this character breaks a particular rule' situations, like races, etc. And to handle things like this: https://www.drivethrurpg.com/product/262129/Cepheus-Light-Traits 
In the long run, traits would most likely have Active Effects (like, 'if you have Claws, your Unarmed attack does +1d6', or whatever.)

**Comment by xdy** [comment]
Fixed by #306

**Comment by jonepatr** [comment]
This issue should be closed, right?

**Comment by xdy** [comment]
Yep!
