### ISSUE TITLE
Add support for PDFoundry

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#60]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to link to pdfs, and particular pages.

**Describe the solution you'd like**
Support all of pdfoundry.

**Describe alternatives you've considered**
Enter screendumps or extracted text in a journal or something.

**Additional context**
How to do it is described here: https://djphoenix719.github.io/PDFoundry/index.html

**Comment by marvin9257** [comment]
I think this is complete
