### ISSUE TITLE
Add support for Cepheus Deluxe Lifeblood and Stamina

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#615]
**Is your feature request related to a problem? Please describe.**
The solution for Barbaric! and Cepheus Quantum won't work.

**Describe the solution you'd like**
For them to work and be visible on the character sheet.

**Describe alternatives you've considered**
N/A

**Additional context**
See https://www.drivethrurpg.com/product/371216/Cepheus-Deluxe-Reference?manufacturers_id=9571 for details

**Comment by marvin9257** [comment]
I think pull request #661 more or less provides most of the functionality.  The only thing to do is add wound and unconscious rolls; and DM for being wounded

**Comment by marvin9257** [comment]
Added wounded icons with update 0.12.0
