### ISSUE TITLE
Add Support for Custom Characteristics 

### ISSUE THREAD

**Issue by ethawyn** [xdy/twodsix-foundryvtt#797]
_Is your feature request related to a problem? Please describe._
No, simply to a limit of the current system in relation to the version of Traveller I wish to run. 

_Describe the solution you'd like_
Add support for custom characteristics so as to be able to support GMs using optional characteristics such as those presented in the Mongoose Traveller Companion.  

_Describe alternatives you've considered_
Perhaps some kind of custom asset/item that could represent the special characteristics could be used. 

_Additional context_
In the Traveller Companion, several unique characteristics such as Sanity are presented as options. Being able to customize the character sheet to add these would be nice.

**Comment by marvin9257** [comment]
There is this capability now - go to systems settings - advanced rules settings.  near bottom is a check box to show alternative characteristics (instead of PSI) and fields to name them whatever you want.  They will work just like any other characteristic.

**Comment by ethawyn** [comment]
Thank you. Tried looking for it and missed it!
