### ISSUE TITLE
Layer Controls Do Not Function

### ISSUE THREAD

**Issue by ethawyn** [xdy/twodsix-foundryvtt#805]
**Before you create the bug report**
* Have you checked that this issue hasn't already been reported on https://github.com/xdy/twodsix-foundryvtt/issues?
* Have you tried with all Foundry modules disabled?
* Have you tried to update your browser? (Do note that Safari is not supported).

**Describe the bug**
On a fresh install of TwodSix 1.4.5 on Foundry Version 9.242 hosted on MoltenHosting with no modules installed, the layer controls do not work. The have a visual hover state when I hover the mouse over them, but clicking does nothing. I have tested on both Chrome and Firefox. I tested it on the desktop as well in case it was a MoltenHosting problem and had the same issue. 

All other controls in Foundry work.

**To Reproduce**
1. Open Foundry VTT version 9.242
2. Create or open a world running TwodSix 1.4.5
3. Attempt to use any of the layer controls. 

**Expected behavior**
Clicking on individual layer controls should bring up the layer tools and I should then be able to select and use the layer tools. 

**Environment (please complete the following information):**
 - OS and browser: Windows 10, Chrome or Firefox. 
 - Foundry Run on Molten Hosting, problem also tested on Desktop Client. 
 - Foundry Version 9.242
 - Twodsix 1.4.5
 - No modules installed on Desktop instance, no modules activated on MoltenHosting instance.

**Comment by marvin9257** [comment]
Hi, when you first create a new world, there is no initial canvas.  You first need to create a scene (map). Then you can use layers.

**Comment by ethawyn** [comment]
Well that works. I feel incredibly stupid.

**Comment by marvin9257** [comment]
Not a problem! Good luck with the system.
