### ISSUE TITLE
Detailed Ships Cargo Management

### ISSUE THREAD

**Issue by MindFlayerZ** [xdy/twodsix-foundryvtt#807]
**Is your feature request related to a problem? Please describe.**
In its current form, the Cargo section of the Ship Sheet is just a basic text field. This lacks the granularity and standardization that may be needed for a long term campaign.

**Describe the solution you'd like**
It would be nice for the ship's Cargo area get the same or similar treatment as Locker.

It would be also useful to have a more "generic" cargo item type for things that fall outside of what's already available. This would also allow the GM to easily drag/drop a  piece of planned cargo onto the ship.

Possible cargo item data:
- name
- weight
- value
- legality
- purchase price
- description
- notes

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by marvin9257** [comment]
Completed with #865
