### ISSUE TITLE
Customizable and dragable damageroll

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#809]
**Is your feature request related to a problem? Please describe.**
It's not possible to roll Damage with a custom DM or Advantage/Disadvantage and drag it to a target. 
ex.: Effect is added to "Destructive"-roll (xDD) only when taget is of a smaller scale.

**Describe the solution you'd like**
When "automatic roll damage" is disabled, the normal roll-dialog should open, when rolling damage via actorsheet. The following chat-output should be dragable. 

Additional feature: The effect of the previous attack-roll should be auto-inserted into the "Other modifiers"- field or into a additional "Effect"-field.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by marvin9257** [comment]
This issue addressed fully in #1025
