### ISSUE TITLE
reference Ship Sheet Positions

### ISSUE THREAD

**Issue by loakesie** [xdy/twodsix-foundryvtt#811]
FOLLOWS ON FROM CONVERSATION WITH jonepatr (conversation cut and paste)
Hi, thoughts on the ship sheet and positions having messed about with it a bit last night. firstly, really good, can't wait to use it in my game  :slight_smile: It looks for the specific skill listed, could you have it so it defaults to untrained if the skill is not present? (thinking specifically for JoT or desperately using the triple beam laser with no one with Turret skill)  In the Macro/Skill space I see we can put /8+ to default the difficulty setting for the given skill, can we do something similar to default the stat modifier and also add any immediate modifiers? In this slot, it would be great if we could put in a  Script Macro to be triggered (I have some macros, eg 'Disperse Sand' when a sandcaster is used it will add the gunners effect to 1d6 to be added to the ships armour value), with the Fire Energy weapon, will this eventually be able to apply damage direct to the Ship's Hull rating modified by armour? Again, thanks guys

Just as a point of note, not that it would be an issue with my players (and hopefully no one else's either) but the players are able to move each others icon in the ship sheet, positions and make their action rolls

sorry there's more. when you do a PopOut the tabs move and I know how you guys like things looking just right, also you can't scroll down. appreciate thus may be module thing not Twodsix I lied, you can scroll down

jonepatr — Today at 12:20
If you are using the untrained skill then you could drag that in, but I see what you mean, and yeah, blank could be left to be untrained. 
How would you the syntax look like for adding modifiers? Gun Combat/DEX+3+5 10+

Originally the actions were built to work with macros (and it worked!). However for security reasons we chose to go with a list of actions instead, and we would add actions as needed in the future. Having only macros also made it a bit unclear what to do if the settings only allow the GM to run macros. But we could add that as a feature. I think that a setting where it warns you about the security issues, and if you tick it another option will appear allowing you to drag in macros as well. Would that work for your use case? 

Yeah, the idea is to develop the fire energy weapons and various rulesets, so that it would apply damage etc. This PR mostly provided the basic framework and so people can start using it. Now we can start developing more actions
Haven't actually thought about what happens if a player doesn't have viewing rights to other players in the ship sheet. Does it still work?

**Comment by marvin9257** [comment]
PR #942 defaults to untrained skill if available and nothing matches from formula

**Comment by marvin9257** [comment]
PR #1330 adds macro option to actions.  Will close this one.
