### ISSUE TITLE
Auto Damage switch push to all players 

### ISSUE THREAD

**Issue by Rouros** [xdy/twodsix-foundryvtt#825]
**Is your feature request related to a problem? Please describe.**
Sometimes auto damage is not turned on on a players user account. This is a pain as I often have to talk a no IT literate person.

**Describe the solution you'd like**
I'd like to turn it on for all players, not just for me, the DM. When the DM ticks the auto damage box in system settings, She should be able to push that change out to her players accounts too.

Perhaps when I select the tick box as the DM, I could have a dialogue pop up to ask if I would like to push that to all currently logged in players.. or to all players..?

**Describe alternatives you've considered**
Manually talking players though making the change themselves.

**Additional context**
If the feature request relates to rules, quotes from and/or links to **OGL** rules (such as Cepheus Engine) are very helpful as we cannot implement features for non-OGL rulesets.

![image](https://user-images.githubusercontent.com/96803351/150531775-8b061d60-d1e4-4171-916d-34c97e23600e.png)

**Comment by jonepatr** [comment]
So perhaps we could do this for any setting that has the scope "client" (i.e. player setting). Currently this is the only player setting, but I think a gm would want to be able to do that for any other setting that is on the player level? @marvin9257 what do you think?

**Comment by xdy** [comment]
As a workaround this module works well for this sort of thing: https://foundryvtt.com/packages/force-client-settings
