### ISSUE TITLE
Change names of characteristics for nonhuman Travellers

### ISSUE THREAD

**Issue by muranternet** [xdy/twodsix-foundryvtt#826]
Some nonhuman traveller species have different characteristics. For example, Hivers do not have SOC but do have RES, which humans do not have. In addition some GMs may have different characteristics for AIs, custom sophonts, etc.

Using the built-in custom characteristics advanced option causes clutter in these cases since all sheets will have headings for unused characteristics, and you are limited to two (one if you reserve the first for PSI).

Suggest an editable species template that is implemented when species is selected by dropdown list where characteristic names can be customized.

**Comment by marvin9257** [comment]
This was addressed when flexible characteristics were added.
