### ISSUE TITLE
Macro text color unreadable

### ISSUE THREAD

**Issue by FOXTetsuo** [xdy/twodsix-foundryvtt#831]
The text used to create macro's is unreadable because of how similar it is to the background.

To Reproduce
1. Click on the hotbar to create a new macro
2. Type text into the "command" section

**Screenshots**
![image](https://user-images.githubusercontent.com/6
![macro](https://user-images.githubusercontent.com/60584659/150877094-feaf87fe-2f5a-411a-95c5-4607977b69c8.png)
0584659/150877015-5eae26c3-ca07-4e16-b640-69ffb161b7fe.png)

**Comment by marvin9257** [comment]
This is likely a class with another module.  If you are using advanced macros, try the setting under the Twodsix debug settings - correct css issues

**Comment by FOXTetsuo** [comment]
Thank you for your very fast response, you're correct, that was the issue. However, the CSS fix does not fix it, disabling the module of course does. Thank you for your time

**Comment by marvin9257** [comment]
No worries. If you let me know the module, I can try to add it to the fixes.

**Comment by FOXTetsuo** [comment]
My apologies, I forgot to say! The culprit was indeed advanced macros.

**Comment by marvin9257** [comment]
closed with #835
