### ISSUE TITLE
Skill Rolls do not raise dialog, throws error

### ISSUE THREAD

**Issue by rreuter-dgtest** [xdy/twodsix-foundryvtt#850]
In v 1.10.0, Chrome 97.0.4692.99 for Windows, selecting a skill from the character sheet does not display a roll dialogue, error is shown in the console. 

To reproduce:

- Open a character sheet and select Skills tab
- Click a skill name
- No dialog to make the skill roll will be shown, and error is shown in the console (Please see attached screen capture):
![Screenshot 2022-01-29 142012](https://user-images.githubusercontent.com/17576400/151674618-3113cf25-cbae-4164-89f8-ff942e0d8f81.jpg)

**Comment by marvin9257** [comment]
It is fixed in 1.10.1 - sorry for that.
