### ISSUE TITLE
I want the system macros to be included with each release! I'm too lazy to fetch them myself!

### ISSUE THREAD

**Issue by xdy** [xdy/twodsix-foundryvtt#852]
**Is your feature request related to a problem? Please describe.**
I want the system macros to be included with each release! I'm too lazy to fetch them myself!

**Describe the solution you'd like**
We really should get those macros into the system properly. (As in, stuff them in a compendium).
It can be done manually, but that would make maintaining them a hassle. I'm too lazy for hassles, so...

Take a look at this commit for the basics on how to do it: https://github.com/xdy/xdy-pf2e-workbench/commit/8c735fe74acf41954aedaabc6069fd88867abb17
Ignore the submodule stuff, the usecase for xdy-pf2e-workbench was to pull in the latest version of external macros, these are already in the repo, so just point to them where they already are instead of fetching them from github.
Would probably be a good idea to also take a look at this: https://github.com/xdy/xdy-pf2e-workbench/commit/43d251194c1f692ad38691ff45337f19b8fa67ec
So as to get hotbar macros that 'update automatically' on new releases (actually, they just call the newly updated macro so they never need to be updated.)

**Describe alternatives you've considered**
Keep doing it manually...

**Additional context**
See above.

**Comment by marvin9257** [comment]
Macros now part of installed compendium.  Macro files on wiki no longer supported.
