### ISSUE TITLE
Ship-Sheet requests

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#875]
Just a collection of my players and me:

- There is no field for the overall Techlevel of the ship. Many rules using this techlevel (ex.: build, repair, upgrade the ship).

- Component-list: Rename "Unit Power Draw" to "Power" and put a "+" or "-" to every component to show if die draw or produce power. 

- Components: Make selectable (ex.: via checkbox) if the component draw or produce power. There can be items which are not integrated into the automation.

- Component-list: Please remove the "Short Description". Many Components have long names (ex.: Rapid Deployment Extended Arrays) and it is nicer when there is no line brake. Most component names are self-explanatory

**Comment by marvin9257** [comment]
I don't understand the use case for this one: 

> Components: Make selectable (ex.: via checkbox) if the component draw or produce power. There can be items which are not integrated into the automation.

You can't list the item in the power component section?

**Comment by marvin9257** [comment]
Add in release #877
