### ISSUE TITLE
GM-Notes

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#959]
**Requested Feature:**
GM-Notes! A textarea only visible/editable for GMs.

Most Systems/VTTs have such a option.

**Alternatives:** 
Using the journal, notes, etc. but it quickly becomes confusing because it is not easy to assign to a specific thing

**Comment by marvin9257** [comment]
This capability exists now in the journal.  There is a "secret" format under custom format (first pull down of the TinyMCE editor.  If you give your players observer permission I think it is hidden from them.
