### ISSUE TITLE
QoL Suggestions

### ISSUE THREAD

**Issue by RomKre** [xdy/twodsix-foundryvtt#977]
Some suggestions from me and my players;

1. Shipsheet: Display fuel-type (refined or unrefined) under the fuelbar and maybe make the type switchable via mouseclick. I think it is possible to replace "current/max" with "Refined" / "Unrefined". Best solution would be, to display the fueltype inside the bar (and make it switchable).

2. Actors/Settings: Please make a setting to define the standard unit and range for the actor-movement. When prepearing an adventure or campaign you have to switch/check the movement and change it for many many actors/npcs - specifically when using metric units.

3. Roll Dialog: Display the used skill, the actual formula, skill and characteristics DM. So you can doublecheck and starter could learn the mechanics quicker. 
The used skill is shown, but it should be more visible. Most roll-errors in my groups are because the weapon has the wrong or not the "untrained" skill selected. This will really help!

4. Actors: Make a standard "Unarmed" weapon-item for all actors and give it to them when created. Damage could be defined via settings. Most actor-type characters have this "weapon", but it must always be created separately.

5. Items/Components: Please make it selectable (via item settings) if "Rating", "Rad Damage"  or "Short Description" are shown,

6. Components listing: Please make the height of the rows always the same. just a design issue and better readable :)

7. Skills/Actors: When dragging/dropping a skill, out of a compendium to an actor, please use the level/value already entered inside the compendium-skill. So you dont have to change the level from 0 to 1, when adding a specialized skill . This onlky works when using compendium-skills with entered levels.

**Comment by marvin9257** [comment]
Some thoughts - 
1) I can look into this and see what is possible in terms of display
2) It gets tricky to mod existing actors and may cause compatibility problems. I can do this when new actors are created.
3) It is really already there for skill rolls (see https://discord.com/channels/739941799820394606/799336208752574504/967770858951180318 and the image there)
4) I'm not certain on this one.  There are other default skills (such as athletics) but are somewhat dependent on the rules set.
5) Rating is used for the short listing - so it is always displayed.  Rad damage is only shown for armaments.  Short description is no longer used for components (and not shown).
6) If I do this, I will have to remove the hits buttons or not show the damage rolls.  It really is only different for armaments or when folks type in long ratings. 
7) Let me look to see if this is possible.  It may conflict with JOAT and untrained settings.

**Comment by RomKre** [comment]
1. Thanks. This would be a really cool feature.
2. I think it is ok, if only new actors are effected. 
3. I know, but I mean it should be displayed before the roll is done - to see if the skill is wrong and so on. It is displayed, but easy to overlook. 
4. I'm not talkign about a skill. Every actor can make an attack unarmed/natural attack. So I have to give every actor a weapon called "Unarmed" with a 1d6 damage. Instead every new actor could get this weapon automatically.
5. "Short Description" are shown in some item-sheets. But this is point is really unimportant :)
6. You could make all heights like that one from the rows   with hit/damage. Higher - not lower.
7. Ok!

Thanks for your patience, energy and passion :)

**Comment by marvin9257** [comment]
7. addressed by #992

**Comment by marvin9257** [comment]
4. addressed by #1002

**Comment by marvin9257** [comment]
6. partially addressed in #1003

**Comment by marvin9257** [comment]
All but 5) implemented
